// This file was auto-generated by Fern from our API Definition.

export interface PostV1InventoryLandedCostsCreateResponse {
    id: string;
    date: string;
    amount: string;
    method: PostV1InventoryLandedCostsCreateResponse.Method;
    goodsReceiptId: string | null;
    sourceInvoiceId: string | null;
    notes: string | null;
    createdAt: string;
    lines: PostV1InventoryLandedCostsCreateResponse.Lines.Item[];
}

export namespace PostV1InventoryLandedCostsCreateResponse {
    export const Method = {
        ByValue: "by_value",
        ByQuantity: "by_quantity",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            movementId: string;
            allocatedAmount: string;
            newUnitCost: string;
        }
    }
}
