// This file was auto-generated by Fern from our API Definition.

export interface PostV1InventoryStockTransferResponse {
    outMovementId: string;
    inMovementId: string;
    totalCost: string;
}
