// This file was auto-generated by Fern from our API Definition.

export interface ApiKeysListAccountResponse {
    rows: ApiKeysListAccountResponse.Rows.Item[];
}

export namespace ApiKeysListAccountResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            name: string;
            scopes: string[];
            lastUsedAt: string | null;
            expiresAt: string | null;
            replacedByKeyId: string | null;
            createdByUserId: string | null;
            revokedAt: string | null;
            createdAt: string;
        }
    }
}
