// This file was auto-generated by Fern from our API Definition.

export interface PostV1AccountTableSettingsListResponse {
    rows: PostV1AccountTableSettingsListResponse.Rows.Item[];
}

export namespace PostV1AccountTableSettingsListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            tableKey: string;
            columns: string[] | null;
            pageSize: number | null;
        }
    }
}
