// This file was auto-generated by Fern from our API Definition.

export interface ReferralConvertAccountResponse {
    points: number;
    amountCents: number;
    pointsLeft: number;
    balanceCents: number;
}
