// This file was auto-generated by Fern from our API Definition.

export interface AnnualAccountsSignaturesUpdateDeclarationsResponse {
    id: string;
    directorName: string;
    directorType: AnnualAccountsSignaturesUpdateDeclarationsResponse.DirectorType;
    signed: boolean;
    signedOn: string | null;
    signedAt: string | null;
    reasonNotSigned: string | null;
}

export namespace AnnualAccountsSignaturesUpdateDeclarationsResponse {
    export const DirectorType = {
        ManagingCurrent: "managing_current",
        ManagingFormer: "managing_former",
        SupervisoryCurrent: "supervisory_current",
        SupervisoryFormer: "supervisory_former",
    } as const;
    export type DirectorType = (typeof DirectorType)[keyof typeof DirectorType];
}
