// This file was auto-generated by Fern from our API Definition.

export interface EeEmploymentRegisterSendDeclarationsResponse {
    reference: string;
    state: EeEmploymentRegisterSendDeclarationsResponse.State;
    detail: string | null;
    fileName: string;
    entryDate: string;
    xml: string;
    warnings: string[];
}

export namespace EeEmploymentRegisterSendDeclarationsResponse {
    export const State = {
        Submitted: "submitted",
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
