// This file was auto-generated by Fern from our API Definition.

export interface LtIntrastatObligationDeclarationsResponse {
    year: number;
    isVatPayer: boolean;
    notes: string[];
    thresholds: LtIntrastatObligationDeclarationsResponse.Thresholds;
    arrivals: LtIntrastatObligationDeclarationsResponse.Arrivals;
    dispatches: LtIntrastatObligationDeclarationsResponse.Dispatches;
}

export namespace LtIntrastatObligationDeclarationsResponse {
    export interface Thresholds {
        arrivalsReporting: string;
        dispatchesReporting: string;
        arrivalsStatistical: string;
        dispatchesStatistical: string;
    }

    export interface Arrivals {
        previousYearValue: string;
        obligatedFromMonth: number | null;
        statisticalValueRequired: boolean;
        monthly: Arrivals.Monthly.Item[];
    }

    export namespace Arrivals {
        export type Monthly = Monthly.Item[];

        export namespace Monthly {
            export interface Item {
                month: number;
                value: string;
                cumulative: string;
            }
        }
    }

    export interface Dispatches {
        previousYearValue: string;
        obligatedFromMonth: number | null;
        statisticalValueRequired: boolean;
        monthly: Dispatches.Monthly.Item[];
    }

    export namespace Dispatches {
        export type Monthly = Monthly.Item[];

        export namespace Monthly {
            export interface Item {
                month: number;
                value: string;
                cumulative: string;
            }
        }
    }
}
