// This file was auto-generated by Fern from our API Definition.

export interface LtIntrastatComputeDeclarationsResponse {
    flow: LtIntrastatComputeDeclarationsResponse.Flow;
    referencePeriod: string;
    periodStart: string;
    periodEnd: string;
    fileName: string;
    fileId: string | null;
    rows: LtIntrastatComputeDeclarationsResponse.Rows.Item[];
    totals: LtIntrastatComputeDeclarationsResponse.Totals;
    counts: LtIntrastatComputeDeclarationsResponse.Counts;
    warnings: string[];
    notes: string[];
    xml: string;
}

export namespace LtIntrastatComputeDeclarationsResponse {
    export const Flow = {
        Arrivals: "arrivals",
        Dispatches: "dispatches",
    } as const;
    export type Flow = (typeof Flow)[keyof typeof Flow];
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            itemNumber: number;
            cnCode: string;
            description: string | null;
            transactionNature: string;
            deliveryTerms: string | null;
            transportMode: string | null;
            regionCode: string | null;
            country: string;
            originCountry: string | null;
            partnerVat: string | null;
            netMassKg: string;
            supplementaryUnit: string | null;
            supplementaryQty: string | null;
            invoicedValue: string;
            statisticalValue: string;
        }
    }

    export interface Totals {
        invoicedValue: string;
        statisticalValue: string;
        netMassKg: string;
        lines: number;
    }

    export interface Counts {
        invoices: number;
        linesIncluded: number;
        linesSkipped: number;
    }
}
