// This file was auto-generated by Fern from our API Definition.

export interface LtSaftGenerateDeclarationsResponse {
    fileName: string;
    fileId: string | null;
    periodStart: string;
    periodEnd: string;
    counts: LtSaftGenerateDeclarationsResponse.Counts;
    warnings: string[];
    xml: string;
}

export namespace LtSaftGenerateDeclarationsResponse {
    export interface Counts {
        accounts: number;
        customers: number;
        suppliers: number;
        glTransactions: number;
        salesInvoices: number;
        purchaseInvoices: number;
        payments: number;
        stockMovements: number;
        assetTransactions: number;
    }
}
