// This file was auto-generated by Fern from our API Definition.

export interface PlCit8GenerateDeclarationsResponse {
    year: number;
    periodStart: string;
    periodEnd: string;
    fileName: string;
    xml: string;
    positions: PlCit8GenerateDeclarationsResponse.Positions.Item[];
    annexes: string[];
    warnings: string[];
    notes: string[];
    source: string;
}

export namespace PlCit8GenerateDeclarationsResponse {
    export type Positions = Positions.Item[];

    export namespace Positions {
        export interface Item {
            field: string;
            label: string;
            value: string;
        }
    }
}
