// This file was auto-generated by Fern from our API Definition.

export interface PlKsefReceivedListDeclarationsResponse {
    rows: PlKsefReceivedListDeclarationsResponse.Rows.Item[];
}

export namespace PlKsefReceivedListDeclarationsResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            ksefReferenceNumber: string;
            invoiceNumber: string | null;
            issuerNip: string | null;
            issueDate: string | null;
            acquisitionTimestamp: string | null;
            grossAmount: string | null;
            purchaseInvoiceId: string | null;
        }
    }
}
