// This file was auto-generated by Fern from our API Definition.

export interface PlKsefReceiptDeclarationsResponse {
    referenceNumber: string;
    state: PlKsefReceiptDeclarationsResponse.State;
    detail: string | null;
    invoiceCount: number | null;
    upoXml: string | null;
}

export namespace PlKsefReceiptDeclarationsResponse {
    export const State = {
        Sent: "sent",
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
