// This file was auto-generated by Fern from our API Definition.

export interface PostV1DeclarationsSubmissionsMarkResponse {
    id: string;
    obligation: string;
    periodYear: number;
    periodMonth: number | null;
    variant: string | null;
    status: PostV1DeclarationsSubmissionsMarkResponse.Status;
    fileName: string;
    fileId: string | null;
    externalRef: string | null;
    message: string | null;
    createdAt: string;
    updatedAt: string;
}

export namespace PostV1DeclarationsSubmissionsMarkResponse {
    export const Status = {
        Generated: "generated",
        Submitted: "submitted",
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
