// This file was auto-generated by Fern from our API Definition.

export interface PostV1DeclarationsLtSaftSendResponse {
    caseId: string;
    state: PostV1DeclarationsLtSaftSendResponse.State;
    detail: string | null;
    fileName: string;
    confirmed: boolean;
    warnings: string[];
}

export namespace PostV1DeclarationsLtSaftSendResponse {
    export const State = {
        Submitted: "submitted",
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
