// This file was auto-generated by Fern from our API Definition.

export interface PostV1DeclarationsLtPln204ComputeResponse {
    year: number;
    periodStart: string;
    periodEnd: string;
    variant: PostV1DeclarationsLtPln204ComputeResponse.Variant;
    registrationNumber: string;
    companyName: string;
    ratePercent: string;
    rateCode: string;
    smallEntity: boolean;
    criteria: PostV1DeclarationsLtPln204ComputeResponse.Criteria;
    totalIncome: string;
    boxes: Record<string, string>;
    annexS: PostV1DeclarationsLtPln204ComputeResponse.AnnexS.Item[];
    annexZ: PostV1DeclarationsLtPln204ComputeResponse.AnnexZ.Item[];
    lines: PostV1DeclarationsLtPln204ComputeResponse.Lines.Item[];
    warnings: string[];
    notes: string[];
    source: string;
}

export namespace PostV1DeclarationsLtPln204ComputeResponse {
    export const Variant = {
        Pln204: "PLN204",
        Pln204A: "PLN204A",
    } as const;
    export type Variant = (typeof Variant)[keyof typeof Variant];

    export interface Criteria {
        netTurnover: string;
        avgEmployees: number;
    }

    export type AnnexS = AnnexS.Item[];

    export namespace AnnexS {
        export interface Item {
            code: string;
            amount: string;
            description: string;
        }
    }

    export type AnnexZ = AnnexZ.Item[];

    export namespace AnnexZ {
        export interface Item {
            code: string;
            amount: string;
            description: string;
        }
    }

    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            key: string;
            label: string;
            value: string;
        }
    }
}
