// This file was auto-generated by Fern from our API Definition.

export interface ReportsListPosResponse {
    rows: ReportsListPosResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
}

export namespace ReportsListPosResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            reportNumber: string;
            date: string;
            deviceId: string | null;
            warehouseId: string | null;
            netTotal: string;
            vatTotal: string;
            grossTotal: string;
            cashAmount: string;
            cardAmount: string;
            cogsTotal: string | null;
            journalTransactionId: string | null;
            notes: string | null;
            createdAt: string;
        }
    }
}
