// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         serialNumber: "serialNumber"
 *     }
 */
export interface PostV1PosDevicesCreateRequest {
    name: string;
    serialNumber: string;
    model?: string;
    registrationNumber?: string;
    address?: string;
}
