// This file was auto-generated by Fern from our API Definition.

export interface ItemsKindsUpdateCatalogResponse {
    id: string;
    code: string;
    name: string;
    saftType: ItemsKindsUpdateCatalogResponse.SaftType;
    quantityAccounting: boolean;
    sortOrder: number;
    createdAt: string;
}

export namespace ItemsKindsUpdateCatalogResponse {
    export const SaftType = {
        Goods: "goods",
        Service: "service",
        FixedAsset: "fixed_asset",
        Other: "other",
    } as const;
    export type SaftType = (typeof SaftType)[keyof typeof SaftType];
}
