// This file was auto-generated by Fern from our API Definition.

export interface PriceListsItemsListCatalogResponse {
    rows: PriceListsItemsListCatalogResponse.Rows.Item[];
}

export namespace PriceListsItemsListCatalogResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            itemId: string;
            itemName: string;
            itemCode: string | null;
            unitPriceExclVat: string;
        }
    }
}
