// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponse {
    error: ErrorResponse.Error_;
}

export namespace ErrorResponse {
    export interface Error_ {
        code: Error_.Code;
        message: string;
        requestId: string;
        fieldErrors?: Record<string, string[]> | undefined;
    }

    export namespace Error_ {
        export const Code = {
            Validation: "validation",
            Unauthorized: "unauthorized",
            Forbidden: "forbidden",
            NotFound: "not_found",
            Conflict: "conflict",
            IdempotencyKeyReuse: "idempotency_key_reuse",
            IdempotencyInProgress: "idempotency_in_progress",
            RateLimited: "rate_limited",
            Internal: "internal",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
