// This file was auto-generated by Fern from our API Definition.

export interface PostV1FleetAssignmentsCreateResponse {
    id: string;
    vehicleId: string;
    plateNumber: string;
    employeeId: string;
    employeeName: string;
    fromDate: string;
    toDate: string | null;
    privateUse: boolean;
    employerPaysFuel: boolean;
    notes: string | null;
    createdAt: string;
}
