export type { AssetsCreateAssetsRequest } from "./AssetsCreateAssetsRequest.js";
export { AssetsDisposeAssetsRequest } from "./AssetsDisposeAssetsRequest.js";
export type { AssetsGetAssetsRequest } from "./AssetsGetAssetsRequest.js";
export { AssetsInputVatAssetsRequest } from "./AssetsInputVatAssetsRequest.js";
export { AssetsListAssetsRequest } from "./AssetsListAssetsRequest.js";
export type { AssetsModernizeAssetsRequest } from "./AssetsModernizeAssetsRequest.js";
export type { AssetsUpdateAssetsRequest } from "./AssetsUpdateAssetsRequest.js";
export type { DepreciationPostAssetsRequest } from "./DepreciationPostAssetsRequest.js";
export type { DepreciationPreviewAssetsRequest } from "./DepreciationPreviewAssetsRequest.js";
export type { GroupsCreateAssetsRequest } from "./GroupsCreateAssetsRequest.js";
export { GroupsListAssetsRequest } from "./GroupsListAssetsRequest.js";
