// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         accountCode: "accountCode",
 *         fromDate: "fromDate",
 *         toDate: "toDate"
 *     }
 */
export interface PostV1ReportsGlDetailRequest {
    accountCode: string;
    fromDate: string;
    toDate: string;
}
