// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fromDate: "fromDate",
 *         toDate: "toDate"
 *     }
 */
export interface PostV1ReportsFinancialStatementsRequest {
    fromDate: string;
    toDate: string;
    category?: PostV1ReportsFinancialStatementsRequest.Category;
}

export namespace PostV1ReportsFinancialStatementsRequest {
    export const Category = {
        Micro: "micro",
        Small: "small",
        Medium: "medium",
        Large: "large",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
