// This file was auto-generated by Fern from our API Definition.

export interface PostV1ProjectsTimeEntriesUpdateResponse {
    id: string;
    projectId: string;
    employeeId: string | null;
    date: string;
    hours: string;
    description: string | null;
    billable: boolean;
    hourlyRate: string | null;
    billedInvoiceId: string | null;
    createdAt: string;
    updatedAt: string;
}
