// This file was auto-generated by Fern from our API Definition.

export interface UpdateProjectsResponse {
    id: string;
    code: string;
    name: string;
    partnerId: string | null;
    status: UpdateProjectsResponse.Status;
    notes: string | null;
    createdAt: string;
    updatedAt: string;
}

export namespace UpdateProjectsResponse {
    export const Status = {
        Active: "active",
        Completed: "completed",
        Archived: "archived",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
