// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NordletApi from "../../../index.js";

export declare namespace BillingClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BillingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillingClient.Options>;

    constructor(options: BillingClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {NordletApi.AccountGetBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.accountGet()
     */
    public accountGet(
        request: NordletApi.AccountGetBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.AccountGetBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__accountGet(request, requestOptions));
    }

    private async __accountGet(
        request: NordletApi.AccountGetBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.AccountGetBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/account/get",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NordletApi.AccountGetBillingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/billing/account/get");
    }

    /**
     * @param {NordletApi.AccountSetPlanBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.accountSetPlan({
     *         plan: "starter"
     *     })
     */
    public accountSetPlan(
        request: NordletApi.AccountSetPlanBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.AccountSetPlanBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__accountSetPlan(request, requestOptions));
    }

    private async __accountSetPlan(
        request: NordletApi.AccountSetPlanBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.AccountSetPlanBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/account/set-plan",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.AccountSetPlanBillingResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/billing/account/set-plan");
    }

    /**
     * @param {NordletApi.TopupCreateBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.topupCreate({
     *         amountCents: 1000000
     *     })
     */
    public topupCreate(
        request: NordletApi.TopupCreateBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.TopupCreateBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__topupCreate(request, requestOptions));
    }

    private async __topupCreate(
        request: NordletApi.TopupCreateBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.TopupCreateBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/topup/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.TopupCreateBillingResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/billing/topup/create");
    }

    /**
     * @param {NordletApi.PortalCreateBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.portalCreate()
     */
    public portalCreate(
        request: NordletApi.PortalCreateBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PortalCreateBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__portalCreate(request, requestOptions));
    }

    private async __portalCreate(
        request: NordletApi.PortalCreateBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PortalCreateBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/portal/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PortalCreateBillingResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/billing/portal/create");
    }

    /**
     * @param {NordletApi.TransactionsListBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.transactionsList()
     */
    public transactionsList(
        request: NordletApi.TransactionsListBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.TransactionsListBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__transactionsList(request, requestOptions));
    }

    private async __transactionsList(
        request: NordletApi.TransactionsListBillingRequest = {},
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.TransactionsListBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/transactions/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.TransactionsListBillingResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/billing/transactions/list",
        );
    }

    /**
     * @param {NordletApi.UsageListBillingRequest} request
     * @param {BillingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.billing.usageList({
     *         from: "2026-07-01",
     *         to: "2026-07-01"
     *     })
     */
    public usageList(
        request: NordletApi.UsageListBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.UsageListBillingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__usageList(request, requestOptions));
    }

    private async __usageList(
        request: NordletApi.UsageListBillingRequest,
        requestOptions?: BillingClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.UsageListBillingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/billing/usage/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as NordletApi.UsageListBillingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/billing/usage/list");
    }
}
