// This file was auto-generated by Fern from our API Definition.

export interface GroupsGetConsolidationResponse {
    id: string;
    name: string;
    presentationCurrency: string;
    memberCount: number;
    createdAt: string;
    updatedAt: string;
    members: GroupsGetConsolidationResponse.Members.Item[];
}

export namespace GroupsGetConsolidationResponse {
    export type Members = Members.Item[];

    export namespace Members {
        export interface Item {
            memberCompanyId: string;
            name: string;
            baseCurrency: string;
            ownershipPercent: string;
            method: Item.Method;
        }

        export namespace Item {
            export const Method = {
                Full: "full",
                Proportional: "proportional",
                Equity: "equity",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }
}
