// This file was auto-generated by Fern from our API Definition.

export interface IntercompanyCandidatesConsolidationResponse {
    rows: IntercompanyCandidatesConsolidationResponse.Rows.Item[];
}

export namespace IntercompanyCandidatesConsolidationResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            memberCompanyId: string;
            memberName: string;
            partnerId: string;
            partnerName: string;
            partnerCode: string | null;
            matchesCompanyId: string;
            matchesCompanyName: string;
            matchedOn: Item.MatchedOn;
            linkId: string | null;
        }

        export namespace Item {
            export const MatchedOn = {
                Code: "code",
                VatCode: "vatCode",
            } as const;
            export type MatchedOn = (typeof MatchedOn)[keyof typeof MatchedOn];
        }
    }
}
