// This file was auto-generated by Fern from our API Definition.

export interface PostV1ConsolidationReportResponse {
    presentationCurrency: string;
    fromDate: string;
    toDate: string;
    category: PostV1ConsolidationReportResponse.Category;
    statements: PostV1ConsolidationReportResponse.Statements;
    trialBalance: PostV1ConsolidationReportResponse.TrialBalance.Item[];
    nonControllingInterest: PostV1ConsolidationReportResponse.NonControllingInterest;
    equityMethod: PostV1ConsolidationReportResponse.EquityMethod;
    members: PostV1ConsolidationReportResponse.Members.Item[];
    eliminations: PostV1ConsolidationReportResponse.Eliminations;
    intercompanyCandidates: PostV1ConsolidationReportResponse.IntercompanyCandidates.Item[];
}

export namespace PostV1ConsolidationReportResponse {
    export const Category = {
        Micro: "micro",
        Small: "small",
        Medium: "medium",
        Large: "large",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];

    export interface Statements {
        category: Statements.Category;
        layout: string;
        requiredStatements: string[];
        asOf: string;
        balanceSheet: Statements.BalanceSheet;
        profitLoss: Statements.ProfitLoss;
        balanceSheetDetail?: Statements.BalanceSheetDetail | undefined;
        profitLossDetail?: Statements.ProfitLossDetail | undefined;
    }

    export namespace Statements {
        export const Category = {
            Micro: "micro",
            Small: "small",
            Medium: "medium",
            Large: "large",
        } as const;
        export type Category = (typeof Category)[keyof typeof Category];

        export interface BalanceSheet {
            nonCurrentAssets: string;
            currentAssets: string;
            totalAssets: string;
            equity: string;
            ofWhichResult: string;
            liabilities: string;
            totalEquityAndLiabilities: string;
            balanced: boolean;
        }

        export interface ProfitLoss {
            fromDate: string;
            toDate: string;
            revenue: string;
            expenses: string;
            netResult: string;
        }

        export interface BalanceSheetDetail {
            nonCurrentAssets: BalanceSheetDetail.NonCurrentAssets;
            currentAssets: BalanceSheetDetail.CurrentAssets;
            equity: BalanceSheetDetail.Equity;
            liabilities: BalanceSheetDetail.Liabilities;
        }

        export namespace BalanceSheetDetail {
            export interface NonCurrentAssets {
                intangible: string;
                tangible: string;
                financial: string;
                other: string;
                total: string;
            }

            export interface CurrentAssets {
                inventories: string;
                receivables: string;
                otherCurrent: string;
                cash: string;
                total: string;
            }

            export interface Equity {
                capital: string;
                reserves: string;
                retainedEarnings: string;
                otherEquity: string;
                periodResult: string;
                total: string;
            }

            export interface Liabilities {
                nonCurrent: string;
                current: string;
                other: string;
                total: string;
            }
        }

        export interface ProfitLossDetail {
            salesRevenue: string;
            costOfSales: string;
            grossProfit: string;
            sellingExpenses: string;
            adminExpenses: string;
            operatingProfit: string;
            otherActivityResult: string;
            financialActivityResult: string;
            profitBeforeTax: string;
            incomeTax: string;
            netProfit: string;
        }
    }

    export type TrialBalance = TrialBalance.Item[];

    export namespace TrialBalance {
        export interface Item {
            code: string;
            type: string;
            closing: string;
            period: string;
        }
    }

    export interface NonControllingInterest {
        equity: string;
        result: string;
    }

    export interface EquityMethod {
        investmentsInAssociates: string;
        shareOfAssociatesResult: string;
    }

    export type Members = Members.Item[];

    export namespace Members {
        export interface Item {
            companyId: string;
            name: string;
            baseCurrency: string;
            ownershipPercent: string;
            method: Item.Method;
            fxFactor: string;
            rateFrom: string;
            rateTo: string;
            totalAssets: string;
            netEquity: string;
            periodResult: string;
        }

        export namespace Item {
            export const Method = {
                Full: "full",
                Proportional: "proportional",
                Equity: "equity",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    export interface Eliminations {
        applied: Eliminations.Applied.Item[];
        balanced: boolean;
        net: string;
    }

    export namespace Eliminations {
        export type Applied = Applied.Item[];

        export namespace Applied {
            export interface Item {
                code: string;
                amount: string;
                note?: string | undefined;
            }
        }
    }

    export type IntercompanyCandidates = IntercompanyCandidates.Item[];

    export namespace IntercompanyCandidates {
        export interface Item {
            memberCompanyId: string;
            memberName: string;
            partnerId: string;
            partnerName: string;
            partnerCode: string | null;
            matchesCompanyId: string;
            matchesCompanyName: string;
            matchedOn: Item.MatchedOn;
        }

        export namespace Item {
            export const MatchedOn = {
                Code: "code",
                VatCode: "vatCode",
            } as const;
            export type MatchedOn = (typeof MatchedOn)[keyof typeof MatchedOn];
        }
    }
}
