// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReferenceComplianceVersionsListResponse {
    rows: PostV1ReferenceComplianceVersionsListResponse.Rows.Item[];
}

export namespace PostV1ReferenceComplianceVersionsListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            country: string;
            system: string;
            artifact: string;
            version: string;
            verifiedOn: string;
            source: string;
            resource?: string | undefined;
            notes?: string | undefined;
        }
    }
}
