// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReferenceLtMunicipalitiesListResponse {
    rows: PostV1ReferenceLtMunicipalitiesListResponse.Rows.Item[];
}

export namespace PostV1ReferenceLtMunicipalitiesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            code: string;
            name: string;
            countyCode: string;
        }
    }
}
