// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReferenceEuVatRatesListResponse {
    rows: PostV1ReferenceEuVatRatesListResponse.Rows.Item[];
}

export namespace PostV1ReferenceEuVatRatesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            countryCode: string;
            category: Item.Category;
            ratePercent: string;
            validFrom: string | null;
            validTo: string | null;
        }

        export namespace Item {
            export const Category = {
                Standard: "standard",
                Reduced: "reduced",
                SuperReduced: "super_reduced",
                Parking: "parking",
            } as const;
            export type Category = (typeof Category)[keyof typeof Category];
        }
    }
}
