// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReferenceCurrenciesListResponse {
    rows: PostV1ReferenceCurrenciesListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
}

export namespace PostV1ReferenceCurrenciesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            code: string;
            name: string;
            minorUnits: number;
        }
    }
}
