// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         partnerId: "partnerId",
 *         lines: [{}]
 *     }
 */
export interface PostV1SalesInvoicesCreateRequest {
    partnerId: string;
    type?: PostV1SalesInvoicesCreateRequest.Type;
    currency?: string;
    issueDate?: string;
    dueDate?: string;
    creditedInvoiceId?: string;
    vatScheme?: PostV1SalesInvoicesCreateRequest.VatScheme;
    vatCountryCode?: string;
    deemedSupplier?: boolean;
    notes?: string;
    lines: PostV1SalesInvoicesCreateRequest.Lines.Item[];
}

export namespace PostV1SalesInvoicesCreateRequest {
    export const Type = {
        Invoice: "invoice",
        CreditNote: "credit_note",
        Proforma: "proforma",
        Advance: "advance",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const VatScheme = {
        Domestic: "domestic",
        IntraEuB2B: "intra_eu_b2b",
        ReverseCharge: "reverse_charge",
        OssUnion: "oss_union",
        Ioss: "ioss",
        MarketplaceDeemed: "marketplace_deemed",
        Export: "export",
        OutOfScope: "out_of_scope",
    } as const;
    export type VatScheme = (typeof VatScheme)[keyof typeof VatScheme];
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            itemId?: string | undefined;
            description?: string | undefined;
            unit?: string | undefined;
            quantity?: Item.Quantity | undefined;
            unitPriceExclVat?: string | undefined;
            unitPriceInclVat?: string | undefined;
            vatRatePercent?: string | undefined;
            vatClassifierCode?: string | undefined;
            costCenterId?: string | undefined;
        }

        export namespace Item {
            export type Quantity = number | string;
        }
    }
}
