// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface RecognitionRunSalesRequest {
    asOfDate?: string;
    postingDate?: string;
    scheduleIds?: string[];
}
