// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         invoiceId: "invoiceId",
 *         estimatedTotal: "121.0000"
 *     }
 */
export interface RefundLiabilityTrueUpSalesRequest {
    invoiceId: string;
    estimatedTotal: string;
    date?: string;
}
