// This file was auto-generated by Fern from our API Definition.

export interface GetCalendarResponse {
    key: string;
    id: string | null;
    kind: GetCalendarResponse.Kind;
    ruleKey: string | null;
    period: string | null;
    title: string;
    dueDate: string;
    notes: string | null;
    done: boolean;
    href: string | null;
    submission: GetCalendarResponse.Submission | null;
    submissions: GetCalendarResponse.Submissions.Item[];
    canSubmit: boolean;
    canAmend: boolean;
    canDownload: boolean;
    automated: boolean;
}

export namespace GetCalendarResponse {
    export const Kind = {
        Custom: "custom",
        Obligation: "obligation",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];

    export interface Submission {
        id: string;
        obligation: string;
        periodYear: number;
        periodMonth: number | null;
        variant: string | null;
        status: Submission.Status;
        fileName: string;
        fileId: string | null;
        externalRef: string | null;
        message: string | null;
        ruleKey: string | null;
        period: string | null;
        documentKey: string | null;
        amendment: number;
        origin: string;
        transportSystem: string | null;
        environment: Submission.Environment | null;
        submittedAt: string | null;
        acceptedAt: string | null;
        rejectedAt: string | null;
        checkedAt: string | null;
        nextCheckAt: string | null;
        attempts: number;
        deliveryError: string | null;
        sentSha256: string | null;
        certificateFingerprint: string | null;
        submittedByActorType: string | null;
        submittedByActorId: string | null;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Submission {
        export const Status = {
            Generated: "generated",
            Submitted: "submitted",
            Accepted: "accepted",
            Rejected: "rejected",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
        export const Environment = {
            Test: "test",
            Production: "production",
        } as const;
        export type Environment = (typeof Environment)[keyof typeof Environment];
    }

    export type Submissions = Submissions.Item[];

    export namespace Submissions {
        export interface Item {
            id: string;
            obligation: string;
            periodYear: number;
            periodMonth: number | null;
            variant: string | null;
            status: Item.Status;
            fileName: string;
            fileId: string | null;
            externalRef: string | null;
            message: string | null;
            ruleKey: string | null;
            period: string | null;
            documentKey: string | null;
            amendment: number;
            origin: string;
            transportSystem: string | null;
            environment: Item.Environment | null;
            submittedAt: string | null;
            acceptedAt: string | null;
            rejectedAt: string | null;
            checkedAt: string | null;
            nextCheckAt: string | null;
            attempts: number;
            deliveryError: string | null;
            sentSha256: string | null;
            certificateFingerprint: string | null;
            submittedByActorType: string | null;
            submittedByActorId: string | null;
            createdAt: string;
            updatedAt: string;
        }

        export namespace Item {
            export const Status = {
                Generated: "generated",
                Submitted: "submitted",
                Accepted: "accepted",
                Rejected: "rejected",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export const Environment = {
                Test: "test",
                Production: "production",
            } as const;
            export type Environment = (typeof Environment)[keyof typeof Environment];
        }
    }
}
