// This file was auto-generated by Fern from our API Definition.

export interface PostV1CalendarUpdateResponse {
    key: string;
    id: string | null;
    kind: PostV1CalendarUpdateResponse.Kind;
    ruleKey: string | null;
    period: string | null;
    title: string;
    dueDate: string;
    notes: string | null;
    done: boolean;
    href: string | null;
}

export namespace PostV1CalendarUpdateResponse {
    export const Kind = {
        Custom: "custom",
        Obligation: "obligation",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
