// This file was auto-generated by Fern from our API Definition.

export interface CostCentersUpdateLedgerResponse {
    id: string;
    code: string;
    name: string;
    groupId: string | null;
    groupName: string | null;
    isActive: boolean;
    createdAt: string;
}
