// This file was auto-generated by Fern from our API Definition.

export interface PostV1LedgerPeriodsUnlockResponse {
    id: string;
    year: number;
    month: number;
    status: PostV1LedgerPeriodsUnlockResponse.Status;
}

export namespace PostV1LedgerPeriodsUnlockResponse {
    export const Status = {
        Open: "open",
        Locked: "locked",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
