// This file was auto-generated by Fern from our API Definition.

export interface PostV1LedgerAccountsUpdateResponse {
    id: string;
    code: string;
    name: string;
    translations: Record<string, PostV1LedgerAccountsUpdateResponse.Translations.Value | null> | null;
    type: PostV1LedgerAccountsUpdateResponse.Type;
    parentId: string | null;
    isPostable: boolean;
    createdAt: string;
}

export namespace PostV1LedgerAccountsUpdateResponse {
    export namespace Translations {
        export interface Value {
            name: string;
        }
    }

    export const Type = {
        Asset: "asset",
        Liability: "liability",
        Equity: "equity",
        Income: "income",
        Expense: "expense",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
