// This file was auto-generated by Fern from our API Definition.

export interface CreateOfficersResponse {
    id: string;
    name: string;
    role: CreateOfficersResponse.Role;
    personalCode: string | null;
    birthDate: string | null;
    appointedOn: string | null;
    powerNotary: string | null;
    resignedOn: string | null;
    signsAccounts: boolean;
}

export namespace CreateOfficersResponse {
    export const Role = {
        Director: "director",
        ManagingDirector: "managing_director",
        BoardMember: "board_member",
        BoardChair: "board_chair",
        SupervisoryBoardMember: "supervisory_board_member",
        Secretary: "secretary",
        Representative: "representative",
        Liquidator: "liquidator",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
