// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         taxableBase: "121.00",
 *         date: "2026-07-01"
 *     }
 */
export interface CalcPayrollRequest {
    taxableBase: string;
    date: string;
    applyAllowance?: boolean;
    allowanceOverride?: string;
    pensionAccumulation?: boolean;
    fixedTerm?: boolean;
    benefitInKind?: string;
    options?: Record<string, string>;
}
