// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         runId: "runId",
 *         bankAccountId: "bankAccountId"
 *     }
 */
export interface PaymentsExportPayrollRequest {
    runId: string;
    bankAccountId: string;
    executionDate?: string;
    locale?: PaymentsExportPayrollRequest.Locale;
}

export namespace PaymentsExportPayrollRequest {
    export const Locale = {
        En: "en",
        Lt: "lt",
        De: "de",
    } as const;
    export type Locale = (typeof Locale)[keyof typeof Locale];
}
