// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         partnerId: "partnerId",
 *         iban: "iban",
 *         signatureDate: "2026-07-01"
 *     }
 */
export interface MandatesCreateBankRequest {
    partnerId: string;
    iban: string;
    bic?: string;
    scheme?: MandatesCreateBankRequest.Scheme;
    sequenceType?: MandatesCreateBankRequest.SequenceType;
    signatureDate: string;
    reference?: string;
    debtorName?: string;
    notes?: string;
}

export namespace MandatesCreateBankRequest {
    export const Scheme = {
        Core: "CORE",
        B2B: "B2B",
    } as const;
    export type Scheme = (typeof Scheme)[keyof typeof Scheme];
    export const SequenceType = {
        Recurrent: "recurrent",
        OneOff: "one_off",
    } as const;
    export type SequenceType = (typeof SequenceType)[keyof typeof SequenceType];
}
