// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         bankAccountId: "bankAccountId",
 *         content: "content"
 *     }
 */
export interface PostV1BankStatementsImportRequest {
    bankAccountId: string;
    format?: PostV1BankStatementsImportRequest.Format;
    content: string;
}

export namespace PostV1BankStatementsImportRequest {
    export const Format = {
        Camt053: "camt053",
        Mt940: "mt940",
        StripeCsv: "stripe-csv",
    } as const;
    export type Format = (typeof Format)[keyof typeof Format];
}
