// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         lines: [{
 *                 description: "description",
 *                 quantity: "121.0000",
 *                 unitPriceExclVat: "121.0000"
 *             }]
 *     }
 */
export interface OrdersCreateEcommerceRequest {
    channel?: string;
    externalRef?: string;
    partnerId?: string;
    partner?: OrdersCreateEcommerceRequest.Partner;
    warehouseId?: string;
    currency?: string;
    shipToCountryCode?: string;
    marketplace?: string;
    notes?: string;
    lines: OrdersCreateEcommerceRequest.Lines.Item[];
}

export namespace OrdersCreateEcommerceRequest {
    export interface Partner {
        name: string;
        email?: string | undefined;
        code?: string | undefined;
    }

    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            itemId?: string | undefined;
            description: string;
            quantity: string;
            unitPriceExclVat: string;
            vatRatePercent?: string | undefined;
        }
    }
}
