// This file was auto-generated by Fern from our API Definition.

export interface DeferralsListPurchasesResponse {
    rows: DeferralsListPurchasesResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
    /** The requested totals split by currency code, present when the listed records carry a currency */
    totalsByCurrency?: Record<string, Record<string, string>> | undefined;
}

export namespace DeferralsListPurchasesResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            invoiceId: string;
            invoiceLineId: string;
            scheduleDate: string;
            description: string | null;
            amount: string;
            expenseAccountCode: string;
            prepaidAccountCode: string;
            status: Item.Status;
            journalTransactionId: string | null;
        }

        export namespace Item {
            export const Status = {
                Pending: "pending",
                Posted: "posted",
                Cancelled: "cancelled",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
