// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NordletApi from "../../../index.js";

export declare namespace BankClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BankClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BankClient.Options>;

    constructor(options: BankClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {NordletApi.PostV1BankAccountsCreateRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankAccountsCreate({
     *         name: "name"
     *     })
     */
    public postV1BankAccountsCreate(
        request: NordletApi.PostV1BankAccountsCreateRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankAccountsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankAccountsCreate(request, requestOptions));
    }

    private async __postV1BankAccountsCreate(
        request: NordletApi.PostV1BankAccountsCreateRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankAccountsCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/accounts/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankAccountsCreateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/accounts/create");
    }

    /**
     * @param {NordletApi.PostV1BankAccountsListRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankAccountsList()
     */
    public postV1BankAccountsList(
        request: NordletApi.PostV1BankAccountsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankAccountsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankAccountsList(request, requestOptions));
    }

    private async __postV1BankAccountsList(
        request: NordletApi.PostV1BankAccountsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankAccountsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/accounts/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankAccountsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/accounts/list");
    }

    /**
     * @param {NordletApi.PostV1BankAccountsUpdateRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankAccountsUpdate({
     *         id: "id"
     *     })
     */
    public postV1BankAccountsUpdate(
        request: NordletApi.PostV1BankAccountsUpdateRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankAccountsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankAccountsUpdate(request, requestOptions));
    }

    private async __postV1BankAccountsUpdate(
        request: NordletApi.PostV1BankAccountsUpdateRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankAccountsUpdateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/accounts/update",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankAccountsUpdateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/accounts/update");
    }

    /**
     * @param {NordletApi.PostV1BankTransactionsImportRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankTransactionsImport({
     *         bankAccountId: "bankAccountId",
     *         transactions: [{
     *                 date: "date",
     *                 amount: "amount"
     *             }]
     *     })
     */
    public postV1BankTransactionsImport(
        request: NordletApi.PostV1BankTransactionsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankTransactionsImportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankTransactionsImport(request, requestOptions));
    }

    private async __postV1BankTransactionsImport(
        request: NordletApi.PostV1BankTransactionsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankTransactionsImportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/transactions/import",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankTransactionsImportResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/transactions/import");
    }

    /**
     * @param {NordletApi.PostV1BankStatementsImportRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankStatementsImport({
     *         bankAccountId: "bankAccountId",
     *         content: "content"
     *     })
     */
    public postV1BankStatementsImport(
        request: NordletApi.PostV1BankStatementsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankStatementsImportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankStatementsImport(request, requestOptions));
    }

    private async __postV1BankStatementsImport(
        request: NordletApi.PostV1BankStatementsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankStatementsImportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/statements/import",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankStatementsImportResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/statements/import");
    }

    /**
     * @param {NordletApi.PostV1BankTransactionsListRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankTransactionsList()
     */
    public postV1BankTransactionsList(
        request: NordletApi.PostV1BankTransactionsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankTransactionsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankTransactionsList(request, requestOptions));
    }

    private async __postV1BankTransactionsList(
        request: NordletApi.PostV1BankTransactionsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankTransactionsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/transactions/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankTransactionsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/transactions/list");
    }

    /**
     * @param {NordletApi.PostV1BankTransactionsMatchRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankTransactionsMatch({
     *         transactionId: "transactionId",
     *         documentType: "sale_invoice",
     *         documentId: "documentId"
     *     })
     */
    public postV1BankTransactionsMatch(
        request: NordletApi.PostV1BankTransactionsMatchRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankTransactionsMatchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankTransactionsMatch(request, requestOptions));
    }

    private async __postV1BankTransactionsMatch(
        request: NordletApi.PostV1BankTransactionsMatchRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankTransactionsMatchResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/transactions/match",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankTransactionsMatchResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/transactions/match");
    }

    /**
     * @param {NordletApi.PostV1BankPaymentsExportRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankPaymentsExport({
     *         bankAccountId: "bankAccountId",
     *         purchaseInvoiceIds: ["purchaseInvoiceIds"]
     *     })
     */
    public postV1BankPaymentsExport(
        request: NordletApi.PostV1BankPaymentsExportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankPaymentsExportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankPaymentsExport(request, requestOptions));
    }

    private async __postV1BankPaymentsExport(
        request: NordletApi.PostV1BankPaymentsExportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankPaymentsExportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/payments/export",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankPaymentsExportResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/payments/export");
    }

    /**
     * @param {NordletApi.PostV1BankTransactionsSuggestMatchesRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankTransactionsSuggestMatches({
     *         transactionId: "transactionId"
     *     })
     */
    public postV1BankTransactionsSuggestMatches(
        request: NordletApi.PostV1BankTransactionsSuggestMatchesRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankTransactionsSuggestMatchesResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__postV1BankTransactionsSuggestMatches(request, requestOptions),
        );
    }

    private async __postV1BankTransactionsSuggestMatches(
        request: NordletApi.PostV1BankTransactionsSuggestMatchesRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankTransactionsSuggestMatchesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/transactions/suggest-matches",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankTransactionsSuggestMatchesResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/bank/transactions/suggest-matches",
        );
    }

    /**
     * @param {NordletApi.PostV1BankSettlementsImportRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankSettlementsImport({
     *         bankAccountId: "bankAccountId",
     *         content: "content"
     *     })
     */
    public postV1BankSettlementsImport(
        request: NordletApi.PostV1BankSettlementsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankSettlementsImportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankSettlementsImport(request, requestOptions));
    }

    private async __postV1BankSettlementsImport(
        request: NordletApi.PostV1BankSettlementsImportRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankSettlementsImportResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/settlements/import",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankSettlementsImportResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/settlements/import");
    }

    /**
     * @param {NordletApi.PostV1BankSettlementsListRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankSettlementsList()
     */
    public postV1BankSettlementsList(
        request: NordletApi.PostV1BankSettlementsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankSettlementsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankSettlementsList(request, requestOptions));
    }

    private async __postV1BankSettlementsList(
        request: NordletApi.PostV1BankSettlementsListRequest = {},
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankSettlementsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/settlements/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankSettlementsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/settlements/list");
    }

    /**
     * @param {NordletApi.PostV1BankSettlementsGetRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankSettlementsGet({
     *         id: "id"
     *     })
     */
    public postV1BankSettlementsGet(
        request: NordletApi.PostV1BankSettlementsGetRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankSettlementsGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankSettlementsGet(request, requestOptions));
    }

    private async __postV1BankSettlementsGet(
        request: NordletApi.PostV1BankSettlementsGetRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankSettlementsGetResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/settlements/get",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankSettlementsGetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/settlements/get");
    }

    /**
     * @param {NordletApi.PostV1BankSettlementsMatchRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankSettlementsMatch({
     *         lineId: "lineId"
     *     })
     */
    public postV1BankSettlementsMatch(
        request: NordletApi.PostV1BankSettlementsMatchRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankSettlementsMatchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankSettlementsMatch(request, requestOptions));
    }

    private async __postV1BankSettlementsMatch(
        request: NordletApi.PostV1BankSettlementsMatchRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankSettlementsMatchResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/settlements/match",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankSettlementsMatchResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/settlements/match");
    }

    /**
     * @param {NordletApi.PostV1BankSettlementsPostRequest} request
     * @param {BankClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.bank.postV1BankSettlementsPost({
     *         id: "id"
     *     })
     */
    public postV1BankSettlementsPost(
        request: NordletApi.PostV1BankSettlementsPostRequest,
        requestOptions?: BankClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1BankSettlementsPostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1BankSettlementsPost(request, requestOptions));
    }

    private async __postV1BankSettlementsPost(
        request: NordletApi.PostV1BankSettlementsPostRequest,
        requestOptions?: BankClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1BankSettlementsPostResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/bank/settlements/post",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1BankSettlementsPostResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/bank/settlements/post");
    }
}
