// This file was auto-generated by Fern from our API Definition.

export interface CalcPayrollResponse {
    countryCode: string;
    taxAllowance: string;
    incomeTax: string;
    employeeContributions: string;
    employerContributions: string;
    components: CalcPayrollResponse.Components.Item[];
    net: string;
}

export namespace CalcPayrollResponse {
    export type Components = Components.Item[];

    export namespace Components {
        export interface Item {
            code: string;
            kind: Item.Kind;
            amount: string;
            rate?: string | undefined;
            base?: string | undefined;
        }

        export namespace Item {
            export const Kind = {
                Allowance: "allowance",
                EmployeeTax: "employee_tax",
                EmployeeContribution: "employee_contribution",
                EmployerContribution: "employer_contribution",
                EmployerPayment: "employer_payment",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
        }
    }
}
