// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         policyNumber: "policyNumber",
 *         insuredObject: "insuredObject",
 *         fromDate: "2026-07-01",
 *         toDate: "2026-07-01"
 *     }
 */
export interface InsurancePoliciesCreateAgreementsRequest {
    insurerPartnerId?: string;
    policyNumber: string;
    insuredObject: string;
    fromDate: string;
    toDate: string;
    premium?: string;
    currency?: string;
    notes?: string;
}
