// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         partnerId: "partnerId",
 *         number: "number",
 *         startDate: "startDate"
 *     }
 */
export interface PostV1AgreementsAgreementsCreateRequest {
    typeId?: string;
    partnerId: string;
    number: string;
    name?: string;
    startDate: string;
    endDate?: string;
    autoRenew?: boolean;
    value?: string;
    billingPeriod?: PostV1AgreementsAgreementsCreateRequest.BillingPeriod;
    currency?: string;
    status?: PostV1AgreementsAgreementsCreateRequest.Status;
    notes?: string;
    items?: PostV1AgreementsAgreementsCreateRequest.Items.Item[];
}

export namespace PostV1AgreementsAgreementsCreateRequest {
    export const BillingPeriod = {
        Monthly: "monthly",
        Quarterly: "quarterly",
        Annual: "annual",
    } as const;
    export type BillingPeriod = (typeof BillingPeriod)[keyof typeof BillingPeriod];
    export const Status = {
        Draft: "draft",
        Active: "active",
        Expired: "expired",
        Terminated: "terminated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            itemId?: string | undefined;
            description: string;
            quantity?: string | undefined;
            unitPrice?: string | undefined;
            vatRatePercent?: string | undefined;
        }
    }
}
