// This file was auto-generated by Fern from our API Definition.

export interface InvoicesEinvoiceSendSalesResponse {
    sent: boolean;
    system: string;
    format: string;
    transport: InvoicesEinvoiceSendSalesResponse.Transport;
    messageId: string;
    nationalNumber: string | null;
    status: InvoicesEinvoiceSendSalesResponse.Status;
    detail: string | null;
    fileId: string | null;
    warnings: string[];
}

export namespace InvoicesEinvoiceSendSalesResponse {
    export const Transport = {
        Bridge: "bridge",
        Direct: "direct",
    } as const;
    export type Transport = (typeof Transport)[keyof typeof Transport];
    export const Status = {
        Sent: "sent",
        Accepted: "accepted",
        Rejected: "rejected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
