// This file was auto-generated by Fern from our API Definition.

export interface PostV1SalesInvoicesListResponse {
    rows: PostV1SalesInvoicesListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
}

export namespace PostV1SalesInvoicesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            partnerId: string;
            type: Item.Type;
            status: Item.Status;
            paymentStatus: Item.PaymentStatus;
            series: string | null;
            number: number | null;
            fullNumber: string | null;
            issueDate: string | null;
            dueDate: string | null;
            currency: string;
            netTotal: string;
            vatTotal: string;
            grossTotal: string;
            paidAmount: string;
            journalTransactionId: string | null;
            appliedToInvoiceId: string | null;
            creditedInvoiceId: string | null;
            agreementId: string | null;
            vatScheme: Item.VatScheme | null;
            vatCountryCode: string | null;
            deemedSupplier: boolean;
            notes: string | null;
            createdAt: string;
            updatedAt: string;
        }

        export namespace Item {
            export const Type = {
                Invoice: "invoice",
                CreditNote: "credit_note",
                Proforma: "proforma",
                Advance: "advance",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            export const Status = {
                Draft: "draft",
                Issued: "issued",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export const PaymentStatus = {
                Unpaid: "unpaid",
                Partial: "partial",
                Paid: "paid",
            } as const;
            export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];
            export const VatScheme = {
                Domestic: "domestic",
                IntraEuB2B: "intra_eu_b2b",
                ReverseCharge: "reverse_charge",
                OssUnion: "oss_union",
                Ioss: "ioss",
                MarketplaceDeemed: "marketplace_deemed",
                Export: "export",
                OutOfScope: "out_of_scope",
                SmeExempt: "sme_exempt",
            } as const;
            export type VatScheme = (typeof VatScheme)[keyof typeof VatScheme];
        }
    }
}
