// This file was auto-generated by Fern from our API Definition.

export interface PostV1SalesRecognitionSummaryResponse {
    rows: PostV1SalesRecognitionSummaryResponse.Rows.Item[];
    totals: PostV1SalesRecognitionSummaryResponse.Totals;
}

export namespace PostV1SalesRecognitionSummaryResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            invoiceId: string;
            invoiceFullNumber: string | null;
            invoiceLineId: string;
            lineDescription: string;
            method: Item.Method;
            deferredTotal: string;
            recognizedToDate: string;
            remaining: string;
            pendingCount: number;
            nextScheduleDate: string | null;
        }

        export namespace Item {
            export const Method = {
                PointInTime: "point_in_time",
                Ratable: "ratable",
                Milestone: "milestone",
                PercentComplete: "percent_complete",
            } as const;
            export type Method = (typeof Method)[keyof typeof Method];
        }
    }

    export interface Totals {
        deferredTotal: string;
        recognizedToDate: string;
        remaining: string;
    }
}
