// This file was auto-generated by Fern from our API Definition.

export interface PostV1SalesActsIssueResponse {
    id: string;
    partnerId: string;
    type: PostV1SalesActsIssueResponse.Type;
    status: PostV1SalesActsIssueResponse.Status;
    series: string;
    fullNumber: string | null;
    documentDate: string;
    saleInvoiceId: string | null;
    transferredByName: string | null;
    transferredByTitle: string | null;
    acceptedByName: string | null;
    acceptedByTitle: string | null;
    notes: string | null;
    createdAt: string;
    updatedAt: string;
    lines: PostV1SalesActsIssueResponse.Lines.Item[];
}

export namespace PostV1SalesActsIssueResponse {
    export const Type = {
        Goods: "goods",
        Services: "services",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const Status = {
        Draft: "draft",
        Issued: "issued",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            id: string;
            itemId: string | null;
            description: string;
            unit: string;
            quantity: string;
            unitPriceExclVat: string | null;
            lineNet: string | null;
            sortOrder: number;
        }
    }
}
