// This file was auto-generated by Fern from our API Definition.

export interface RefundLiabilityTrueUpSalesResponse {
    invoiceId: string;
    estimated: string;
    consumed: string;
    remaining: string;
    delta: string;
    journalTransactionId: string;
}
