// This file was auto-generated by Fern from our API Definition.

export interface RefundLiabilityListSalesResponse {
    rows: RefundLiabilityListSalesResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
    /** The requested totals split by currency code, present when the listed records carry a currency */
    totalsByCurrency?: Record<string, Record<string, string>> | undefined;
}

export namespace RefundLiabilityListSalesResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            invoiceId: string;
            invoiceFullNumber: string | null;
            estimated: string;
            consumed: string;
            settlementRefunds: string;
            remaining: string;
            createdAt: string;
            updatedAt: string;
        }
    }
}
