// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "projectId"
 *     }
 */
export interface TimeEntriesBillProjectsRequest {
    projectId: string;
    partnerId?: string;
    dateFrom?: string;
    dateTo?: string;
    itemId?: string;
    hourlyRate?: string;
    vatRatePercent?: string;
    vatClassifierCode?: string;
    issueDate?: string;
    dueDate?: string;
    groupBy?: TimeEntriesBillProjectsRequest.GroupBy;
    notes?: string;
}

export namespace TimeEntriesBillProjectsRequest {
    export const GroupBy = {
        Rate: "rate",
        Entry: "entry",
    } as const;
    export type GroupBy = (typeof GroupBy)[keyof typeof GroupBy];
}
