// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         groupId: "groupId",
 *         id: "id"
 *     }
 */
export interface IntercompanyLinksRemoveConsolidationRequest {
    groupId: string;
    id: string;
}
