// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         year: 1000000,
 *         adopted: true,
 *         dateOfPreparation: "2026-07-01"
 *     }
 */
export interface AnnualAccountsSetDeclarationsRequest {
    year: number;
    adopted: boolean;
    adoptionDate?: string;
    dateOfPreparation: string;
    audited?: boolean;
    auditReportQualified?: boolean;
    auditorNotElected?: boolean;
    notesText?: string;
    managementReportText?: string;
    auditorReportText?: string;
    auditorReportDate?: string;
    resultToReserves?: string;
    resultToLossCompensation?: string;
    resultToRemainder?: string;
}
