// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         ruleKey: "ruleKey",
 *         enabled: true
 *     }
 */
export interface AutomationUpdateDeclarationsRequest {
    ruleKey: string;
    enabled: boolean;
}
