// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         system: "system",
 *         config: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ConfigsUpdateDeclarationsRequest {
    system: string;
    config: Record<string, string>;
}
