export { AnnualAccountsAttachmentsAddDeclarationsRequest } from "./AnnualAccountsAttachmentsAddDeclarationsRequest.js";
export type { AnnualAccountsAttachmentsDeleteDeclarationsRequest } from "./AnnualAccountsAttachmentsDeleteDeclarationsRequest.js";
export { AnnualAccountsDistributionsCreateDeclarationsRequest } from "./AnnualAccountsDistributionsCreateDeclarationsRequest.js";
export type { AnnualAccountsDistributionsDeleteDeclarationsRequest } from "./AnnualAccountsDistributionsDeleteDeclarationsRequest.js";
export { AnnualAccountsDistributionsUpdateDeclarationsRequest } from "./AnnualAccountsDistributionsUpdateDeclarationsRequest.js";
export type { AnnualAccountsGetDeclarationsRequest } from "./AnnualAccountsGetDeclarationsRequest.js";
export type { AnnualAccountsSetDeclarationsRequest } from "./AnnualAccountsSetDeclarationsRequest.js";
export { AnnualAccountsSignaturesCreateDeclarationsRequest } from "./AnnualAccountsSignaturesCreateDeclarationsRequest.js";
export type { AnnualAccountsSignaturesDeleteDeclarationsRequest } from "./AnnualAccountsSignaturesDeleteDeclarationsRequest.js";
export { AnnualAccountsSignaturesUpdateDeclarationsRequest } from "./AnnualAccountsSignaturesUpdateDeclarationsRequest.js";
export type { AutomationListDeclarationsRequest } from "./AutomationListDeclarationsRequest.js";
export type { AutomationUpdateDeclarationsRequest } from "./AutomationUpdateDeclarationsRequest.js";
export { CertificatesDeleteDeclarationsRequest } from "./CertificatesDeleteDeclarationsRequest.js";
export type { CertificatesListDeclarationsRequest } from "./CertificatesListDeclarationsRequest.js";
export type { CertificatesUploadDeclarationsRequest } from "./CertificatesUploadDeclarationsRequest.js";
export type { ConfigsListDeclarationsRequest } from "./ConfigsListDeclarationsRequest.js";
export type { ConfigsUpdateDeclarationsRequest } from "./ConfigsUpdateDeclarationsRequest.js";
export type { CyHe32GenerateDeclarationsRequest } from "./CyHe32GenerateDeclarationsRequest.js";
export type { CyTd4GenerateDeclarationsRequest } from "./CyTd4GenerateDeclarationsRequest.js";
export type { DeBeitragsnachweisGenerateDeclarationsRequest } from "./DeBeitragsnachweisGenerateDeclarationsRequest.js";
export type { DeDeuevGenerateDeclarationsRequest } from "./DeDeuevGenerateDeclarationsRequest.js";
export type { DeReturnFactsGetDeclarationsRequest } from "./DeReturnFactsGetDeclarationsRequest.js";
export { DeReturnFactsSetDeclarationsRequest } from "./DeReturnFactsSetDeclarationsRequest.js";
export { DeReturnsGenerateDeclarationsRequest } from "./DeReturnsGenerateDeclarationsRequest.js";
export type { DkSelskabsskatGenerateDeclarationsRequest } from "./DkSelskabsskatGenerateDeclarationsRequest.js";
export { EeEmploymentRegisterSendDeclarationsRequest } from "./EeEmploymentRegisterSendDeclarationsRequest.js";
export type { EsVerifactuDeclaracionResponsableDeclarationsRequest } from "./EsVerifactuDeclaracionResponsableDeclarationsRequest.js";
export type { EuDac7PreviewDeclarationsRequest } from "./EuDac7PreviewDeclarationsRequest.js";
export type { EuDac7XmlDeclarationsRequest } from "./EuDac7XmlDeclarationsRequest.js";
export type { EuDigitalReportingListDeclarationsRequest } from "./EuDigitalReportingListDeclarationsRequest.js";
export type { EuDistanceSalesThresholdGetDeclarationsRequest } from "./EuDistanceSalesThresholdGetDeclarationsRequest.js";
export type { EuIossComputeDeclarationsRequest } from "./EuIossComputeDeclarationsRequest.js";
export type { EuOssComputeDeclarationsRequest } from "./EuOssComputeDeclarationsRequest.js";
export type { EuOwnGoodsTransfersComputeDeclarationsRequest } from "./EuOwnGoodsTransfersComputeDeclarationsRequest.js";
export type { EuSmeCrossBorderReportComputeDeclarationsRequest } from "./EuSmeCrossBorderReportComputeDeclarationsRequest.js";
export type { EuSmeThresholdGetDeclarationsRequest } from "./EuSmeThresholdGetDeclarationsRequest.js";
export type { EuSmeThresholdsListDeclarationsRequest } from "./EuSmeThresholdsListDeclarationsRequest.js";
export type { EuUnionTurnoverGetDeclarationsRequest } from "./EuUnionTurnoverGetDeclarationsRequest.js";
export type { EuVatReturnComputeDeclarationsRequest } from "./EuVatReturnComputeDeclarationsRequest.js";
export type { EuVatReturnPacksListDeclarationsRequest } from "./EuVatReturnPacksListDeclarationsRequest.js";
export type { IeB1GenerateDeclarationsRequest } from "./IeB1GenerateDeclarationsRequest.js";
export type { IeCt1GenerateDeclarationsRequest } from "./IeCt1GenerateDeclarationsRequest.js";
export { ItSdiPurchasePreviewDeclarationsRequest } from "./ItSdiPurchasePreviewDeclarationsRequest.js";
export { ItSdiPurchaseSendDeclarationsRequest } from "./ItSdiPurchaseSendDeclarationsRequest.js";
export type { LiLohndeklarationGenerateDeclarationsRequest } from "./LiLohndeklarationGenerateDeclarationsRequest.js";
export type { LiLohnlistenGenerateDeclarationsRequest } from "./LiLohnlistenGenerateDeclarationsRequest.js";
export type { LtFr0564ComputeDeclarationsRequest } from "./LtFr0564ComputeDeclarationsRequest.js";
export type { LtFr0600ComputeDeclarationsRequest } from "./LtFr0600ComputeDeclarationsRequest.js";
export { LtGpm312ComputeDeclarationsRequest } from "./LtGpm312ComputeDeclarationsRequest.js";
export { LtGpm313ComputeDeclarationsRequest } from "./LtGpm313ComputeDeclarationsRequest.js";
export { LtIntrastatComputeDeclarationsRequest } from "./LtIntrastatComputeDeclarationsRequest.js";
export type { LtIntrastatObligationDeclarationsRequest } from "./LtIntrastatObligationDeclarationsRequest.js";
export { LtIsafGenerateDeclarationsRequest } from "./LtIsafGenerateDeclarationsRequest.js";
export type { LtIvazAmendDeclarationsRequest } from "./LtIvazAmendDeclarationsRequest.js";
export { LtIvazCancelDeclarationsRequest } from "./LtIvazCancelDeclarationsRequest.js";
export type { LtIvazGenerateDeclarationsRequest } from "./LtIvazGenerateDeclarationsRequest.js";
export type { LtPln204ComputeDeclarationsRequest } from "./LtPln204ComputeDeclarationsRequest.js";
export type { LtPln204FfdataDeclarationsRequest } from "./LtPln204FfdataDeclarationsRequest.js";
export { LtSaftGenerateDeclarationsRequest } from "./LtSaftGenerateDeclarationsRequest.js";
export { LtSaftSendDeclarationsRequest } from "./LtSaftSendDeclarationsRequest.js";
export type { LtSamComputeDeclarationsRequest } from "./LtSamComputeDeclarationsRequest.js";
export { LtSdFfdataDeclarationsRequest } from "./LtSdFfdataDeclarationsRequest.js";
export { LtSdGenerateDeclarationsRequest } from "./LtSdGenerateDeclarationsRequest.js";
export type { MtAnnualReturnGenerateDeclarationsRequest } from "./MtAnnualReturnGenerateDeclarationsRequest.js";
export type { MtCompanyTaxGenerateDeclarationsRequest } from "./MtCompanyTaxGenerateDeclarationsRequest.js";
export type { PlCit8GenerateDeclarationsRequest } from "./PlCit8GenerateDeclarationsRequest.js";
export { PlIntrastatGenerateDeclarationsRequest } from "./PlIntrastatGenerateDeclarationsRequest.js";
export type { PlJpkFaGenerateDeclarationsRequest } from "./PlJpkFaGenerateDeclarationsRequest.js";
export type { PlJpkKrGenerateDeclarationsRequest } from "./PlJpkKrGenerateDeclarationsRequest.js";
export type { PlJpkMagGenerateDeclarationsRequest } from "./PlJpkMagGenerateDeclarationsRequest.js";
export type { PlJpkV7MGenerateDeclarationsRequest } from "./PlJpkV7MGenerateDeclarationsRequest.js";
export type { PlKsefReceiptDeclarationsRequest } from "./PlKsefReceiptDeclarationsRequest.js";
export type { PlKsefReceivedFetchDeclarationsRequest } from "./PlKsefReceivedFetchDeclarationsRequest.js";
export type { PlKsefReceivedListDeclarationsRequest } from "./PlKsefReceivedListDeclarationsRequest.js";
export type { PlPit11GenerateDeclarationsRequest } from "./PlPit11GenerateDeclarationsRequest.js";
export type { PlVatUeGenerateDeclarationsRequest } from "./PlVatUeGenerateDeclarationsRequest.js";
export type { PlZusDraComputeDeclarationsRequest } from "./PlZusDraComputeDeclarationsRequest.js";
export type { PlZusDraKeduDeclarationsRequest } from "./PlZusDraKeduDeclarationsRequest.js";
export type { PlZusDraPdfDeclarationsRequest } from "./PlZusDraPdfDeclarationsRequest.js";
export type { RoEtransportBuildDeclarationsRequest } from "./RoEtransportBuildDeclarationsRequest.js";
export type { RoEtransportStatusDeclarationsRequest } from "./RoEtransportStatusDeclarationsRequest.js";
export type { RoEtransportSubmitDeclarationsRequest } from "./RoEtransportSubmitDeclarationsRequest.js";
export { SubmissionsCreateDeclarationsRequest } from "./SubmissionsCreateDeclarationsRequest.js";
export { SubmissionsListDeclarationsRequest } from "./SubmissionsListDeclarationsRequest.js";
export { SubmissionsMarkDeclarationsRequest } from "./SubmissionsMarkDeclarationsRequest.js";
export type { SubmissionsRetryDeclarationsRequest } from "./SubmissionsRetryDeclarationsRequest.js";
export { TaxAdjustmentsCreateDeclarationsRequest } from "./TaxAdjustmentsCreateDeclarationsRequest.js";
export type { TaxAdjustmentsDeleteDeclarationsRequest } from "./TaxAdjustmentsDeleteDeclarationsRequest.js";
export type { TaxAdjustmentsListDeclarationsRequest } from "./TaxAdjustmentsListDeclarationsRequest.js";
export { TaxAdjustmentsUpdateDeclarationsRequest } from "./TaxAdjustmentsUpdateDeclarationsRequest.js";
export { TaxPaymentsCreateDeclarationsRequest } from "./TaxPaymentsCreateDeclarationsRequest.js";
export type { TaxPaymentsDeleteDeclarationsRequest } from "./TaxPaymentsDeleteDeclarationsRequest.js";
export { TaxPaymentsListDeclarationsRequest } from "./TaxPaymentsListDeclarationsRequest.js";
export { TaxPaymentsUpdateDeclarationsRequest } from "./TaxPaymentsUpdateDeclarationsRequest.js";
