// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         year: 1000000,
 *         month: 1000000,
 *         flow: "arrivals"
 *     }
 */
export interface LtIntrastatComputeDeclarationsRequest {
    year: number;
    month: number;
    flow: LtIntrastatComputeDeclarationsRequest.Flow;
    transactionNature?: string;
    deliveryTerms?: string;
    transportMode?: LtIntrastatComputeDeclarationsRequest.TransportMode;
    regionCode?: string;
    statisticalValueRequired?: boolean;
    preparationTimeHours?: number;
    preparationTimeMinutes?: number;
    persist?: boolean;
}

export namespace LtIntrastatComputeDeclarationsRequest {
    export const Flow = {
        Arrivals: "arrivals",
        Dispatches: "dispatches",
    } as const;
    export type Flow = (typeof Flow)[keyof typeof Flow];
    export const TransportMode = {
        One: "1",
        Two: "2",
        Three: "3",
        Four: "4",
        Five: "5",
        Seven: "7",
        Eight: "8",
        Nine: "9",
    } as const;
    export type TransportMode = (typeof TransportMode)[keyof typeof TransportMode];
}
