// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         waybillIds: ["waybillIds"]
 *     }
 */
export interface LtIvazAmendDeclarationsRequest {
    waybillIds: string[];
    persist?: boolean;
}
