// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fromDate: "2026-07-01",
 *         toDate: "2026-07-01"
 *     }
 */
export interface LtSaftSendDeclarationsRequest {
    fromDate: string;
    toDate: string;
    dataType?: LtSaftSendDeclarationsRequest.DataType;
    confirm?: boolean;
    amend?: boolean;
}

export namespace LtSaftSendDeclarationsRequest {
    export const DataType = {
        F: "F",
        Gl: "GL",
        Si: "SI",
        Pi: "PI",
        Pa: "PA",
        Mg: "MG",
        As: "AS",
    } as const;
    export type DataType = (typeof DataType)[keyof typeof DataType];
}
