// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dateFrom: "2026-07-01",
 *         dateTo: "2026-07-01"
 *     }
 */
export interface PlJpkMagGenerateDeclarationsRequest {
    dateFrom: string;
    dateTo: string;
    warehouseId?: string;
}
