// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         year: 1000000
 *     }
 */
export interface PostV1DeclarationsLtIntrastatObligationRequest {
    year: number;
}
