// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         year: 1000000,
 *         kind: "non_deductible",
 *         amount: "amount",
 *         description: "description"
 *     }
 */
export interface PostV1DeclarationsTaxAdjustmentsCreateRequest {
    year: number;
    kind: PostV1DeclarationsTaxAdjustmentsCreateRequest.Kind;
    code?: string;
    amount: string;
    description: string;
}

export namespace PostV1DeclarationsTaxAdjustmentsCreateRequest {
    export const Kind = {
        NonDeductible: "non_deductible",
        IncomeIncrease: "income_increase",
        NonTaxableIncome: "non_taxable_income",
        ExcludedIncome: "excluded_income",
        DeductibleAdjustment: "deductible_adjustment",
        Donation: "donation",
        LossCarriedForward: "loss_carried_forward",
        InvestmentRelief: "investment_relief",
        ForeignTaxCredit: "foreign_tax_credit",
        TaxReduction: "tax_reduction",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
