// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         purchaseInvoiceId: "purchaseInvoiceId"
 *     }
 */
export interface PostV1DeclarationsItSdiPurchasePreviewRequest {
    purchaseInvoiceId: string;
    vatRatePercent?: string;
    tipoDocumento?: PostV1DeclarationsItSdiPurchasePreviewRequest.TipoDocumento;
}

export namespace PostV1DeclarationsItSdiPurchasePreviewRequest {
    export const TipoDocumento = {
        Td16: "TD16",
        Td17: "TD17",
        Td18: "TD18",
        Td19: "TD19",
    } as const;
    export type TipoDocumento = (typeof TipoDocumento)[keyof typeof TipoDocumento];
}
