// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fromDate: "fromDate",
 *         toDate: "toDate"
 *     }
 */
export interface PostV1DeclarationsLtSaftSendRequest {
    fromDate: string;
    toDate: string;
    dataType?: PostV1DeclarationsLtSaftSendRequest.DataType;
    confirm?: boolean;
}

export namespace PostV1DeclarationsLtSaftSendRequest {
    export const DataType = {
        F: "F",
        Gl: "GL",
        Si: "SI",
        Pi: "PI",
        Pa: "PA",
        Mg: "MG",
        As: "AS",
    } as const;
    export type DataType = (typeof DataType)[keyof typeof DataType];
}
