// This file was auto-generated by Fern from our API Definition.

export interface OrdersReserveEcommerceResponse {
    id: string;
    channel: string;
    externalRef: string | null;
    partnerId: string;
    warehouseId: string | null;
    currency: string;
    status: OrdersReserveEcommerceResponse.Status;
    invoiceId: string | null;
    shipToCountryCode: string | null;
    marketplace: string | null;
    notes: string | null;
    createdAt: string;
    lines: OrdersReserveEcommerceResponse.Lines.Item[];
}

export namespace OrdersReserveEcommerceResponse {
    export const Status = {
        New: "new",
        Reserved: "reserved",
        Fulfilled: "fulfilled",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            id: string;
            itemId: string | null;
            description: string;
            quantity: string;
            unitPriceExclVat: string;
            vatRatePercent: string;
        }
    }
}
