// This file was auto-generated by Fern from our API Definition.

export interface PostV1EcommerceOrdersListResponse {
    rows: PostV1EcommerceOrdersListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
}

export namespace PostV1EcommerceOrdersListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            channel: string;
            externalRef: string | null;
            partnerId: string;
            warehouseId: string | null;
            currency: string;
            status: Item.Status;
            invoiceId: string | null;
            shipToCountryCode: string | null;
            marketplace: string | null;
            notes: string | null;
            createdAt: string;
        }

        export namespace Item {
            export const Status = {
                New: "new",
                Reserved: "reserved",
                Fulfilled: "fulfilled",
                Cancelled: "cancelled",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
