// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         partnerId: "partnerId"
 *     }
 */
export interface AddressesCreatePartnersRequest {
    type?: AddressesCreatePartnersRequest.Type;
    street?: string;
    city?: string;
    postalCode?: string;
    countryCode?: string;
    isDefault?: boolean;
    partnerId: string;
}

export namespace AddressesCreatePartnersRequest {
    export const Type = {
        Billing: "billing",
        Shipping: "shipping",
        Registered: "registered",
        Other: "other",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
