// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ContactsUpdatePartnersRequest {
    name?: string;
    role?: string;
    email?: string;
    phone?: string;
    notes?: string;
    id: string;
}
