export { PostV1PartnersAddressesCreateRequest } from "./PostV1PartnersAddressesCreateRequest.js";
export type { PostV1PartnersAddressesDeleteRequest } from "./PostV1PartnersAddressesDeleteRequest.js";
export { PostV1PartnersAddressesListRequest } from "./PostV1PartnersAddressesListRequest.js";
export { PostV1PartnersAddressesUpdateRequest } from "./PostV1PartnersAddressesUpdateRequest.js";
export type { PostV1PartnersBankAccountsCreateRequest } from "./PostV1PartnersBankAccountsCreateRequest.js";
export type { PostV1PartnersBankAccountsDeleteRequest } from "./PostV1PartnersBankAccountsDeleteRequest.js";
export { PostV1PartnersBankAccountsListRequest } from "./PostV1PartnersBankAccountsListRequest.js";
export type { PostV1PartnersBankAccountsUpdateRequest } from "./PostV1PartnersBankAccountsUpdateRequest.js";
export type { PostV1PartnersContactsCreateRequest } from "./PostV1PartnersContactsCreateRequest.js";
export type { PostV1PartnersContactsDeleteRequest } from "./PostV1PartnersContactsDeleteRequest.js";
export { PostV1PartnersContactsListRequest } from "./PostV1PartnersContactsListRequest.js";
export type { PostV1PartnersContactsUpdateRequest } from "./PostV1PartnersContactsUpdateRequest.js";
export { PostV1PartnersCreateRequest } from "./PostV1PartnersCreateRequest.js";
export type { PostV1PartnersCreditCheckRequest } from "./PostV1PartnersCreditCheckRequest.js";
export type { PostV1PartnersDeleteRequest } from "./PostV1PartnersDeleteRequest.js";
export { PostV1PartnersFindOrCreateRequest } from "./PostV1PartnersFindOrCreateRequest.js";
export type { PostV1PartnersGetRequest } from "./PostV1PartnersGetRequest.js";
export type { PostV1PartnersGroupsCreateRequest } from "./PostV1PartnersGroupsCreateRequest.js";
export type { PostV1PartnersGroupsDeleteRequest } from "./PostV1PartnersGroupsDeleteRequest.js";
export type { PostV1PartnersGroupsListRequest } from "./PostV1PartnersGroupsListRequest.js";
export type { PostV1PartnersGroupsUpdateRequest } from "./PostV1PartnersGroupsUpdateRequest.js";
export type { PostV1PartnersInquiriesCreateRequest } from "./PostV1PartnersInquiriesCreateRequest.js";
export type { PostV1PartnersInquiriesGetRequest } from "./PostV1PartnersInquiriesGetRequest.js";
export { PostV1PartnersInquiriesListRequest } from "./PostV1PartnersInquiriesListRequest.js";
export { PostV1PartnersInquiriesUpdateRequest } from "./PostV1PartnersInquiriesUpdateRequest.js";
export { PostV1PartnersListRequest } from "./PostV1PartnersListRequest.js";
export type { PostV1PartnersStatusesCreateRequest } from "./PostV1PartnersStatusesCreateRequest.js";
export type { PostV1PartnersStatusesDeleteRequest } from "./PostV1PartnersStatusesDeleteRequest.js";
export type { PostV1PartnersStatusesListRequest } from "./PostV1PartnersStatusesListRequest.js";
export type { PostV1PartnersStatusesUpdateRequest } from "./PostV1PartnersStatusesUpdateRequest.js";
export { PostV1PartnersUpdateRequest } from "./PostV1PartnersUpdateRequest.js";
export type { PostV1PartnersValidateVatRequest } from "./PostV1PartnersValidateVatRequest.js";
export { PostV1PartnersVatReviewsListRequest } from "./PostV1PartnersVatReviewsListRequest.js";
export { PostV1PartnersVatReviewsResolveRequest } from "./PostV1PartnersVatReviewsResolveRequest.js";
