// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sourceId: "sourceId",
 *         targetId: "targetId"
 *     }
 */
export interface MergePartnersRequest {
    sourceId: string;
    targetId: string;
}
