// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PostV1PartnersBankAccountsUpdateRequest {
    iban?: string;
    bankName?: string;
    bic?: string;
    currency?: string;
    isDefault?: boolean;
    id: string;
}
