// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CompaniesCreateAccountRequest {
    name: string;
    code?: string;
    vatCode?: string;
    smeExemptionNumber?: string;
    isVatPayer?: boolean;
    vatPeriod?: CompaniesCreateAccountRequest.VatPeriod;
    fiscalYearEndMonth?: number;
    timeZone?: string;
    filingOptions?: Record<string, string>;
    address?: CompaniesCreateAccountRequest.Address;
    email?: string;
    phone?: string;
    iban?: string;
    bankName?: string;
    peppolId?: string;
    sepaCreditorId?: string;
    defaultInvoiceCurrency?: string;
    legalForm?: string;
    registryName?: string;
    incorporatedOn?: string;
    shareCapital?: string;
    accountsKeptBy?: CompaniesCreateAccountRequest.AccountsKeptBy;
    bookkeeperName?: string;
    auditorName?: string;
    auditorRegistrationNumber?: string;
    auditRequired?: boolean;
    /** Jurisdiction the company is registered in (immutable after creation) */
    countryCode?: CompaniesCreateAccountRequest.CountryCode;
    /** Currency the ledger is kept in; defaults to the national currency of countryCode (immutable after creation) */
    baseCurrency?: string;
    /** Sandbox companies hold test data and are purged immediately on delete (immutable after creation) */
    isSandbox?: boolean;
}

export namespace CompaniesCreateAccountRequest {
    export const VatPeriod = {
        Monthly: "monthly",
        Bimonthly: "bimonthly",
        Quarterly: "quarterly",
        Semiannual: "semiannual",
        Annual: "annual",
    } as const;
    export type VatPeriod = (typeof VatPeriod)[keyof typeof VatPeriod];

    export interface Address {
        street?: string | undefined;
        city?: string | undefined;
        postalCode?: string | undefined;
        countryCode?: string | undefined;
    }

    export const AccountsKeptBy = {
        Company: "company",
        External: "external",
    } as const;
    export type AccountsKeptBy = (typeof AccountsKeptBy)[keyof typeof AccountsKeptBy];
    /** Jurisdiction the company is registered in (immutable after creation) */
    export const CountryCode = {
        At: "AT",
        Be: "BE",
        Bg: "BG",
        Cy: "CY",
        Cz: "CZ",
        De: "DE",
        Dk: "DK",
        Ee: "EE",
        Es: "ES",
        Fi: "FI",
        Fr: "FR",
        Gr: "GR",
        Hr: "HR",
        Hu: "HU",
        Ie: "IE",
        It: "IT",
        Lt: "LT",
        Lu: "LU",
        Lv: "LV",
        Mt: "MT",
        Nl: "NL",
        Pl: "PL",
        Pt: "PT",
        Ro: "RO",
        Se: "SE",
        Si: "SI",
        Sk: "SK",
        Is: "IS",
        Li: "LI",
        No: "NO",
    } as const;
    export type CountryCode = (typeof CountryCode)[keyof typeof CountryCode];
}
