// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "token"
 *     }
 */
export interface PostV1AccountInvitesAcceptRequest {
    token: string;
    name?: string;
    locale?: PostV1AccountInvitesAcceptRequest.Locale;
    acceptTerms?: boolean;
    acceptDpa?: boolean;
}

export namespace PostV1AccountInvitesAcceptRequest {
    export const Locale = {
        En: "en",
        Lt: "lt",
        De: "de",
    } as const;
    export type Locale = (typeof Locale)[keyof typeof Locale];
}
