// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tableKey: "tableKey"
 *     }
 */
export interface PostV1AccountTableSettingsGetRequest {
    tableKey: string;
}
