// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         result: "passed"
 *     }
 */
export interface QualityChecksRecordProductionRequest {
    id: string;
    result: QualityChecksRecordProductionRequest.Result;
    notes?: string;
}

export namespace QualityChecksRecordProductionRequest {
    export const Result = {
        Passed: "passed",
        Failed: "failed",
    } as const;
    export type Result = (typeof Result)[keyof typeof Result];
}
