// This file was auto-generated by Fern from our API Definition.

export interface PostV1CaptureSettingsRegenerateIntakeResponse {
    intakeEnabled: boolean;
    captureAutoExtract: boolean;
    intakeAddress: string | null;
    ocrConfigured: boolean;
}
