// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         fromWarehouseId: "fromWarehouseId",
 *         toWarehouseId: "toWarehouseId",
 *         itemId: "itemId",
 *         date: "date",
 *         quantity: "quantity"
 *     }
 */
export interface PostV1InventoryStockTransferRequest {
    fromWarehouseId: string;
    toWarehouseId: string;
    itemId: string;
    date: string;
    quantity: string;
    lotNumber?: string;
    notes?: string;
}
