// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PostV1InventoryReorderRulesUpdateRequest {
    id: string;
    minQty?: string;
    reorderQty?: string | null;
    isActive?: boolean;
    notes?: string | null;
}
