// This file was auto-generated by Fern from our API Definition.

export interface WorkCentersUpdateProductionResponse {
    id: string;
    code: string;
    name: string;
    costPerHour: string;
    costAccountCode: string | null;
    maintenanceIntervalDays: number | null;
    nextMaintenanceDate: string | null;
    isActive: boolean;
    notes: string | null;
    createdAt: string;
}
