// This file was auto-generated by Fern from our API Definition.

export interface PostV1FilesUploadResponse {
    id: string;
    entity: string;
    entityId: string;
    fileName: string;
    mimeType: string;
    sizeBytes: number;
    sha256: string;
    createdAt: string;
}
