// This file was auto-generated by Fern from our API Definition.

export interface AgreementsBillingRunAgreementsResponse {
    generated: AgreementsBillingRunAgreementsResponse.Generated.Item[];
    expired: string[];
    errors: AgreementsBillingRunAgreementsResponse.Errors.Item[];
}

export namespace AgreementsBillingRunAgreementsResponse {
    export type Generated = Generated.Item[];

    export namespace Generated {
        export interface Item {
            agreementId: string;
            invoiceId: string;
            periodStart: string;
            periodEnd: string;
        }
    }

    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            agreementId: string;
            message: string;
        }
    }
}
