// This file was auto-generated by Fern from our API Definition.

export interface AgreementsGenerateInvoiceAgreementsResponse {
    invoiceId: string;
    periodStart: string;
    periodEnd: string;
    renewedEndDate: string | null;
}
