// This file was auto-generated by Fern from our API Definition.

export interface PostV1AgreementsAgreementsListResponse {
    rows: PostV1AgreementsAgreementsListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
}

export namespace PostV1AgreementsAgreementsListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            typeId: string | null;
            kind: Item.Kind;
            partnerId: string | null;
            employeeId: string | null;
            bankAccountId: string | null;
            number: string;
            name: string | null;
            startDate: string;
            endDate: string | null;
            autoRenew: boolean;
            value: string | null;
            billingPeriod: Item.BillingPeriod | null;
            currency: string;
            status: Item.Status;
            notes: string | null;
            documentRef: string | null;
            createdAt: string;
        }

        export namespace Item {
            export const Kind = {
                Customer: "customer",
                Supplier: "supplier",
                Employment: "employment",
                Bank: "bank",
                Lease: "lease",
                Insurance: "insurance",
                Other: "other",
            } as const;
            export type Kind = (typeof Kind)[keyof typeof Kind];
            export const BillingPeriod = {
                Monthly: "monthly",
                Quarterly: "quarterly",
                Annual: "annual",
            } as const;
            export type BillingPeriod = (typeof BillingPeriod)[keyof typeof BillingPeriod];
            export const Status = {
                Draft: "draft",
                Active: "active",
                Expired: "expired",
                Terminated: "terminated",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
