// This file was auto-generated by Fern from our API Definition.

export interface PostV1AgreementsAgreementsBillingRunResponse {
    generated: PostV1AgreementsAgreementsBillingRunResponse.Generated.Item[];
    expired: string[];
    errors: PostV1AgreementsAgreementsBillingRunResponse.Errors.Item[];
}

export namespace PostV1AgreementsAgreementsBillingRunResponse {
    export type Generated = Generated.Item[];

    export namespace Generated {
        export interface Item {
            agreementId: string;
            invoiceId: string;
            periodStart: string;
            periodEnd: string;
        }
    }

    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            agreementId: string;
            message: string;
        }
    }
}
