// This file was auto-generated by Fern from our API Definition.

export interface PostV1AgreementsAgreementsUpdateResponse {
    id: string;
    typeId: string | null;
    partnerId: string;
    number: string;
    name: string | null;
    startDate: string;
    endDate: string | null;
    autoRenew: boolean;
    value: string | null;
    currency: string;
    status: PostV1AgreementsAgreementsUpdateResponse.Status;
    notes: string | null;
    createdAt: string;
    items: PostV1AgreementsAgreementsUpdateResponse.Items.Item[];
}

export namespace PostV1AgreementsAgreementsUpdateResponse {
    export const Status = {
        Draft: "draft",
        Active: "active",
        Expired: "expired",
        Terminated: "terminated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            itemId: string | null;
            description: string;
            quantity: string | null;
            unitPrice: string | null;
        }
    }
}
