// This file was auto-generated by Fern from our API Definition.

export interface ExpenseReportsCreateCashResponse {
    id: string;
    number: string;
    employeeId: string;
    date: string;
    netTotal: string;
    vatTotal: string;
    total: string;
    journalTransactionId: string | null;
    notes: string | null;
    createdAt: string;
    lines: ExpenseReportsCreateCashResponse.Lines.Item[];
}

export namespace ExpenseReportsCreateCashResponse {
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            id: string;
            description: string;
            documentNumber: string | null;
            accountCode: string;
            netAmount: string;
            vatAmount: string;
        }
    }
}
