// This file was auto-generated by Fern from our API Definition.

export interface OrdersGetCashResponse {
    id: string;
    type: OrdersGetCashResponse.Type;
    series: string;
    number: number;
    fullNumber: string;
    date: string;
    partnerId: string | null;
    employeeId: string | null;
    amount: string;
    currency: string;
    purpose: string;
    cashAccountCode: string;
    counterAccountCode: string;
    journalTransactionId: string | null;
    saleInvoiceId: string | null;
    purchaseInvoiceId: string | null;
    notes: string | null;
    createdAt: string;
}

export namespace OrdersGetCashResponse {
    export const Type = {
        Receipt: "receipt",
        Disbursement: "disbursement",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
