// This file was auto-generated by Fern from our API Definition.

export interface PostV1CashAdvanceHoldersBalancesResponse {
    rows: PostV1CashAdvanceHoldersBalancesResponse.Rows.Item[];
}

export namespace PostV1CashAdvanceHoldersBalancesResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            employeeId: string;
            firstName: string;
            lastName: string;
            issued: string;
            returned: string;
            balance: string;
        }
    }
}
