// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         itemId: "itemId",
 *         partnerId: "partnerId"
 *     }
 */
export interface ItemsSuppliersUpsertCatalogRequest {
    itemId: string;
    partnerId: string;
    supplierCode?: string;
    purchasePriceExclVat?: string;
    currency?: string;
    notes?: string;
}
