// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "code",
 *         name: "name"
 *     }
 */
export interface PriceListsCreateCatalogRequest {
    code: string;
    name: string;
    currency?: string;
    isActive?: boolean;
}
