// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         priceListId: "priceListId",
 *         itemId: "itemId"
 *     }
 */
export interface PriceListsItemsDeleteCatalogRequest {
    priceListId: string;
    itemId: string;
}
