// This file was auto-generated by Fern from our API Definition.

export interface AccountsListBankResponse {
    rows: AccountsListBankResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
    /** The requested totals split by currency code, present when the listed records carry a currency */
    totalsByCurrency?: Record<string, Record<string, string>> | undefined;
}

export namespace AccountsListBankResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            name: string;
            iban: string | null;
            currency: string;
            accountCode: string;
            isActive: boolean;
            createdAt: string;
        }
    }
}
