// This file was auto-generated by Fern from our API Definition.

export interface ImportTemplatesListBankResponse {
    rows: ImportTemplatesListBankResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
    /** The requested totals split by currency code, present when the listed records carry a currency */
    totalsByCurrency?: Record<string, Record<string, string>> | undefined;
}

export namespace ImportTemplatesListBankResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            name: string;
            type: Item.Type;
            fields: Item.Fields.Item[];
            metaFields: string[];
            invoiceMetaField: string | null;
            invoiceVatRatePercent: string | null;
            companyMetaField: string | null;
            invoiceItemId: string | null;
            advanceInvoices: boolean;
            authorizationOperationTypeId: string | null;
            payoutOperationTypeId: string | null;
            commissionOperationTypeId: string | null;
            lenderMetaField: string | null;
            partialRefundLabel: string | null;
            fullRefundLabel: string | null;
            createdAt: string;
            updatedAt: string;
        }

        export namespace Item {
            export const Type = {
                Stripe: "stripe",
                Iso20022: "iso20022",
                BankConnection: "bank_connection",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            export type Fields = Fields.Item[];

            export namespace Fields {
                export interface Item {
                    name: string;
                    accountCode: string | null;
                    createPartner: boolean;
                }
            }
        }
    }
}
