// This file was auto-generated by Fern from our API Definition.

export interface PostV1BankPaymentsExportResponse {
    messageId: string;
    fileName: string;
    transactionCount: number;
    controlSum: string;
    xml: string;
}
