// This file was auto-generated by Fern from our API Definition.

export interface PostV1BankSettlementsGetResponse {
    id: string;
    bankAccountId: string;
    provider: string;
    payoutId: string;
    payoutDate: string | null;
    currency: string;
    grossTotal: string;
    feeTotal: string;
    netTotal: string;
    status: PostV1BankSettlementsGetResponse.Status;
    journalTransactionId: string | null;
    lineCount: number;
    matchedCount: number;
    unmatchedCount: number;
    createdAt: string;
    updatedAt: string;
    lines: PostV1BankSettlementsGetResponse.Lines.Item[];
}

export namespace PostV1BankSettlementsGetResponse {
    export const Status = {
        Imported: "imported",
        Posted: "posted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Lines = Lines.Item[];

    export namespace Lines {
        export interface Item {
            id: string;
            externalId: string;
            category: string;
            date: string;
            gross: string;
            fee: string;
            net: string;
            description: string | null;
            sourceId: string | null;
            chargeId: string | null;
            reference: string | null;
            matchedInvoiceId: string | null;
            matchStatus: Item.MatchStatus;
        }

        export namespace Item {
            export const MatchStatus = {
                Unmatched: "unmatched",
                Matched: "matched",
                Manual: "manual",
            } as const;
            export type MatchStatus = (typeof MatchStatus)[keyof typeof MatchStatus];
        }
    }
}
