// This file was auto-generated by Fern from our API Definition.

export interface PostV1BankMandatesListResponse {
    rows: PostV1BankMandatesListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
}

export namespace PostV1BankMandatesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            partnerId: string;
            reference: string;
            scheme: Item.Scheme;
            sequenceType: Item.SequenceType;
            status: Item.Status;
            debtorName: string;
            iban: string;
            bic: string | null;
            signatureDate: string;
            collectionsCount: number;
            lastCollectionDate: string | null;
            expiresOn: string;
            cancelledAt: string | null;
            notes: string | null;
            createdAt: string;
        }

        export namespace Item {
            export const Scheme = {
                Core: "CORE",
                B2B: "B2B",
            } as const;
            export type Scheme = (typeof Scheme)[keyof typeof Scheme];
            export const SequenceType = {
                Recurrent: "recurrent",
                OneOff: "one_off",
            } as const;
            export type SequenceType = (typeof SequenceType)[keyof typeof SequenceType];
            export const Status = {
                Active: "active",
                Cancelled: "cancelled",
                Completed: "completed",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
