// This file was auto-generated by Fern from our API Definition.

export interface StatementsImportBankResponse {
    imported: number;
    skipped: number;
    posted: number;
    customersCreated: number;
    invoicesCreated: number;
    invoicesLinked: number;
    creditNotesCreated: number;
    authorizationsRecorded: number;
    payoutsPosted: number;
    commissionsPosted: number;
    paymentsMatched: number;
    warnings: string[];
    statements: StatementsImportBankResponse.Statements.Item[];
}

export namespace StatementsImportBankResponse {
    export type Statements = Statements.Item[];

    export namespace Statements {
        export interface Item {
            statementId: string | null;
            iban: string | null;
            fromDate: string | null;
            toDate: string | null;
            openingBalance: string | null;
            closingBalance: string | null;
            transactionCount: number;
        }
    }
}
