// This file was auto-generated by Fern from our API Definition.

export interface TransactionsMatchManyBankResponse {
    id: string;
    bankAccountId: string;
    date: string;
    amount: string;
    currency: string;
    counterpartyName: string | null;
    counterpartyIban: string | null;
    description: string | null;
    externalId: string | null;
    status: TransactionsMatchManyBankResponse.Status;
    matchedDocumentType: string | null;
    matchedDocumentId: string | null;
    journalTransactionId: string | null;
    createdAt: string;
}

export namespace TransactionsMatchManyBankResponse {
    export const Status = {
        New: "new",
        Matched: "matched",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
