// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NordletApi from "../../../index.js";

export declare namespace FleetClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FleetClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<FleetClient.Options>;

    constructor(options: FleetClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {NordletApi.PostV1FleetVehiclesCreateRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetVehiclesCreate({
     *         plateNumber: "plateNumber",
     *         make: "make",
     *         model: "model"
     *     })
     */
    public postV1FleetVehiclesCreate(
        request: NordletApi.PostV1FleetVehiclesCreateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetVehiclesCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetVehiclesCreate(request, requestOptions));
    }

    private async __postV1FleetVehiclesCreate(
        request: NordletApi.PostV1FleetVehiclesCreateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetVehiclesCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/vehicles/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetVehiclesCreateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/vehicles/create");
    }

    /**
     * @param {NordletApi.PostV1FleetVehiclesUpdateRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetVehiclesUpdate({
     *         id: "id"
     *     })
     */
    public postV1FleetVehiclesUpdate(
        request: NordletApi.PostV1FleetVehiclesUpdateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetVehiclesUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetVehiclesUpdate(request, requestOptions));
    }

    private async __postV1FleetVehiclesUpdate(
        request: NordletApi.PostV1FleetVehiclesUpdateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetVehiclesUpdateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/vehicles/update",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetVehiclesUpdateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/vehicles/update");
    }

    /**
     * @param {NordletApi.PostV1FleetVehiclesGetRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetVehiclesGet({
     *         id: "id"
     *     })
     */
    public postV1FleetVehiclesGet(
        request: NordletApi.PostV1FleetVehiclesGetRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetVehiclesGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetVehiclesGet(request, requestOptions));
    }

    private async __postV1FleetVehiclesGet(
        request: NordletApi.PostV1FleetVehiclesGetRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetVehiclesGetResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/vehicles/get",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetVehiclesGetResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/vehicles/get");
    }

    /**
     * @param {NordletApi.PostV1FleetVehiclesListRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetVehiclesList()
     */
    public postV1FleetVehiclesList(
        request: NordletApi.PostV1FleetVehiclesListRequest = {},
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetVehiclesListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetVehiclesList(request, requestOptions));
    }

    private async __postV1FleetVehiclesList(
        request: NordletApi.PostV1FleetVehiclesListRequest = {},
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetVehiclesListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/vehicles/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetVehiclesListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/vehicles/list");
    }

    /**
     * @param {NordletApi.PostV1FleetAssignmentsCreateRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetAssignmentsCreate({
     *         vehicleId: "vehicleId",
     *         employeeId: "employeeId",
     *         fromDate: "fromDate"
     *     })
     */
    public postV1FleetAssignmentsCreate(
        request: NordletApi.PostV1FleetAssignmentsCreateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetAssignmentsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetAssignmentsCreate(request, requestOptions));
    }

    private async __postV1FleetAssignmentsCreate(
        request: NordletApi.PostV1FleetAssignmentsCreateRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetAssignmentsCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/assignments/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetAssignmentsCreateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/assignments/create");
    }

    /**
     * @param {NordletApi.PostV1FleetAssignmentsEndRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetAssignmentsEnd({
     *         id: "id",
     *         toDate: "toDate"
     *     })
     */
    public postV1FleetAssignmentsEnd(
        request: NordletApi.PostV1FleetAssignmentsEndRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetAssignmentsEndResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetAssignmentsEnd(request, requestOptions));
    }

    private async __postV1FleetAssignmentsEnd(
        request: NordletApi.PostV1FleetAssignmentsEndRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetAssignmentsEndResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/assignments/end",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetAssignmentsEndResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/assignments/end");
    }

    /**
     * @param {NordletApi.PostV1FleetAssignmentsListRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetAssignmentsList()
     */
    public postV1FleetAssignmentsList(
        request: NordletApi.PostV1FleetAssignmentsListRequest = {},
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetAssignmentsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetAssignmentsList(request, requestOptions));
    }

    private async __postV1FleetAssignmentsList(
        request: NordletApi.PostV1FleetAssignmentsListRequest = {},
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetAssignmentsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/assignments/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetAssignmentsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/assignments/list");
    }

    /**
     * @param {NordletApi.PostV1FleetNaturaPreviewRequest} request
     * @param {FleetClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.fleet.postV1FleetNaturaPreview({
     *         year: 1000000,
     *         month: 1000000
     *     })
     */
    public postV1FleetNaturaPreview(
        request: NordletApi.PostV1FleetNaturaPreviewRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1FleetNaturaPreviewResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1FleetNaturaPreview(request, requestOptions));
    }

    private async __postV1FleetNaturaPreview(
        request: NordletApi.PostV1FleetNaturaPreviewRequest,
        requestOptions?: FleetClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1FleetNaturaPreviewResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/fleet/natura/preview",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1FleetNaturaPreviewResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/fleet/natura/preview");
    }
}
