// This file was auto-generated by Fern from our API Definition.

export interface BooksValidateMigrationResponse {
    dryRun: boolean;
    cutoverDate: string;
    accounts: BooksValidateMigrationResponse.Accounts;
    partners: BooksValidateMigrationResponse.Partners;
    items: BooksValidateMigrationResponse.Items;
    assetGroups: BooksValidateMigrationResponse.AssetGroups;
    openingBalances: BooksValidateMigrationResponse.OpeningBalances | null;
    journal: BooksValidateMigrationResponse.Journal;
    openReceivables: BooksValidateMigrationResponse.OpenReceivables;
    openPayables: BooksValidateMigrationResponse.OpenPayables;
    fixedAssets: BooksValidateMigrationResponse.FixedAssets;
    stock: BooksValidateMigrationResponse.Stock;
    numberSeries: BooksValidateMigrationResponse.NumberSeries.Item[];
    warnings: string[];
}

export namespace BooksValidateMigrationResponse {
    export interface Accounts {
        created: number;
        existing: number;
    }

    export interface Partners {
        created: number;
        existing: number;
    }

    export interface Items {
        created: number;
        existing: number;
    }

    export interface AssetGroups {
        created: number;
        existing: number;
    }

    export interface OpeningBalances {
        journalTransactionId: string | null;
        date: string;
        entries: number;
        debitTotal: string;
        creditTotal: string;
        balancingAmount: string;
    }

    export interface Journal {
        transactions: number;
        entries: number;
    }

    export interface OpenReceivables {
        created: number;
        outstandingTotal: string;
    }

    export interface OpenPayables {
        created: number;
        outstandingTotal: string;
    }

    export interface FixedAssets {
        created: number;
        costTotal: string;
        accumulatedDepreciationTotal: string;
    }

    export interface Stock {
        movements: number;
        costTotal: string;
    }

    export type NumberSeries = NumberSeries.Item[];

    export namespace NumberSeries {
        export interface Item {
            prefix: string;
            year: number;
            nextNumber: number;
        }
    }
}
