// This file was auto-generated by Fern from our API Definition.

export interface PostV1PartnersStatusesListResponse {
    rows: PostV1PartnersStatusesListResponse.Rows.Item[];
}

export namespace PostV1PartnersStatusesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            code: string;
            name: string;
            sortOrder: number;
            createdAt: string;
        }
    }
}
