// This file was auto-generated by Fern from our API Definition.

export interface PostV1PartnersAddressesListResponse {
    rows: PostV1PartnersAddressesListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
    totals?: Record<string, string> | undefined;
}

export namespace PostV1PartnersAddressesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            partnerId: string;
            type: string;
            street: string | null;
            city: string | null;
            postalCode: string | null;
            countryCode: string | null;
            isDefault: boolean;
            createdAt: string;
        }
    }
}
