// This file was auto-generated by Fern from our API Definition.

export interface PostV1LeadsFilesListResponse {
    rows: PostV1LeadsFilesListResponse.Rows.Item[];
}

export namespace PostV1LeadsFilesListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            fileName: string;
            mimeType: string;
            sizeBytes: number;
            createdAt: string;
        }
    }
}
