// This file was auto-generated by Fern from our API Definition.

export interface DatevReportsResponse {
    fileName: string;
    contentType: string;
    data: string;
    bookings: number;
    source: string;
    warnings: string[];
    notes: string[];
}
