// This file was auto-generated by Fern from our API Definition.

export interface DebtAgingReportsResponse {
    asOf: string;
    side: string;
    rows: DebtAgingReportsResponse.Rows.Item[];
}

export namespace DebtAgingReportsResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            partnerId: string;
            partnerName: string;
            current: string;
            d1to30: string;
            d31to60: string;
            d61to90: string;
            over90: string;
            total: string;
        }
    }
}
