// This file was auto-generated by Fern from our API Definition.

export interface EuPurchasesReportsResponse {
    fromDate: string;
    toDate: string;
    rows: EuPurchasesReportsResponse.Rows.Item[];
    totals: EuPurchasesReportsResponse.Totals;
}

export namespace EuPurchasesReportsResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            countryCode: string;
            vatRatePercent: string;
            net: string;
            vat: string;
            documents: number;
        }
    }

    export interface Totals {
        net: string;
        vat: string;
    }
}
