// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReportsStockAgingResponse {
    asOf: string;
    rows: PostV1ReportsStockAgingResponse.Rows.Item[];
    totalValue: string;
}

export namespace PostV1ReportsStockAgingResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            itemId: string;
            itemName: string;
            warehouseId: string;
            d0to30Qty: string;
            d0to30Value: string;
            d31to60Qty: string;
            d31to60Value: string;
            d61to90Qty: string;
            d61to90Value: string;
            over90Qty: string;
            over90Value: string;
            totalQty: string;
            totalValue: string;
        }
    }
}
