// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReportsVatSummaryResponse {
    side: string;
    fromDate: string;
    toDate: string;
    rows: PostV1ReportsVatSummaryResponse.Rows.Item[];
    totals: PostV1ReportsVatSummaryResponse.Totals;
}

export namespace PostV1ReportsVatSummaryResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            vatRatePercent: string;
            net: string;
            vat: string;
            gross: string;
            documents: number;
        }
    }

    export interface Totals {
        net: string;
        vat: string;
        gross: string;
    }
}
