// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReportsCashFlowResponse {
    fromDate: string;
    toDate: string;
    openingCash: string;
    closingCash: string;
    netChange: string;
    operating: PostV1ReportsCashFlowResponse.Operating;
    investing: PostV1ReportsCashFlowResponse.Investing;
    financing: PostV1ReportsCashFlowResponse.Financing;
    balanced: boolean;
}

export namespace PostV1ReportsCashFlowResponse {
    export interface Operating {
        inflow: string;
        outflow: string;
        net: string;
        rows: Operating.Rows.Item[];
    }

    export namespace Operating {
        export type Rows = Rows.Item[];

        export namespace Rows {
            export interface Item {
                code: string;
                name: string;
                inflow: string;
                outflow: string;
            }
        }
    }

    export interface Investing {
        inflow: string;
        outflow: string;
        net: string;
        rows: Investing.Rows.Item[];
    }

    export namespace Investing {
        export type Rows = Rows.Item[];

        export namespace Rows {
            export interface Item {
                code: string;
                name: string;
                inflow: string;
                outflow: string;
            }
        }
    }

    export interface Financing {
        inflow: string;
        outflow: string;
        net: string;
        rows: Financing.Rows.Item[];
    }

    export namespace Financing {
        export type Rows = Rows.Item[];

        export namespace Rows {
            export interface Item {
                code: string;
                name: string;
                inflow: string;
                outflow: string;
            }
        }
    }
}
