// This file was auto-generated by Fern from our API Definition.

export interface PostV1ReportsFecResponse {
    fileName: string;
    contentType: string;
    data: string;
    rows: number;
    source: string;
    warnings: string[];
    notes: string[];
}
