// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         code: "code",
 *         name: "name",
 *         type: "asset"
 *     }
 */
export interface AccountsCreateLedgerRequest {
    code: string;
    name: string;
    translations?: Record<string, AccountsCreateLedgerRequest.Translations.Value>;
    type: AccountsCreateLedgerRequest.Type;
    parentId?: string;
    isPostable?: boolean;
}

export namespace AccountsCreateLedgerRequest {
    export namespace Translations {
        export interface Value {
            name: string;
        }
    }

    export const Type = {
        Asset: "asset",
        Liability: "liability",
        Equity: "equity",
        Income: "income",
        Expense: "expense",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
