// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         date: "date",
 *         entries: [{
 *                 accountCode: "accountCode"
 *             }]
 *     }
 */
export interface PostV1LedgerJournalTransactionsCreateRequest {
    date: string;
    description?: string;
    entries: PostV1LedgerJournalTransactionsCreateRequest.Entries.Item[];
}

export namespace PostV1LedgerJournalTransactionsCreateRequest {
    export type Entries = Entries.Item[];

    export namespace Entries {
        export interface Item {
            accountCode: string;
            costCenterId?: string | undefined;
            debit?: string | undefined;
            credit?: string | undefined;
            description?: string | undefined;
        }
    }
}
