// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface PostV1LedgerAccountsUpdateRequest {
    id: string;
    name?: string;
    translations?: PostV1LedgerAccountsUpdateRequest.Translations | null;
    parentId?: string | null;
    isPostable?: boolean;
}

export namespace PostV1LedgerAccountsUpdateRequest {
    export interface Translations {
        lt?: Translations.Lt | undefined;
        en?: Translations.En | undefined;
        ru?: Translations.Ru | undefined;
    }

    export namespace Translations {
        export interface Lt {
            name: string;
        }

        export interface En {
            name: string;
        }

        export interface Ru {
            name: string;
        }
    }
}
