// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NordletApi from "../../../index.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {NordletApi.PostV1WebhooksSubscriptionsCreateRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksSubscriptionsCreate({
     *         url: "url",
     *         events: ["events"]
     *     })
     */
    public postV1WebhooksSubscriptionsCreate(
        request: NordletApi.PostV1WebhooksSubscriptionsCreateRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksSubscriptionsCreateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksSubscriptionsCreate(request, requestOptions));
    }

    private async __postV1WebhooksSubscriptionsCreate(
        request: NordletApi.PostV1WebhooksSubscriptionsCreateRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksSubscriptionsCreateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksSubscriptionsCreateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/create",
        );
    }

    /**
     * @param {NordletApi.PostV1WebhooksSubscriptionsListRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksSubscriptionsList()
     */
    public postV1WebhooksSubscriptionsList(
        request: NordletApi.PostV1WebhooksSubscriptionsListRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksSubscriptionsListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksSubscriptionsList(request, requestOptions));
    }

    private async __postV1WebhooksSubscriptionsList(
        request: NordletApi.PostV1WebhooksSubscriptionsListRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksSubscriptionsListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksSubscriptionsListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/list",
        );
    }

    /**
     * @param {NordletApi.PostV1WebhooksSubscriptionsUpdateRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksSubscriptionsUpdate({
     *         id: "id"
     *     })
     */
    public postV1WebhooksSubscriptionsUpdate(
        request: NordletApi.PostV1WebhooksSubscriptionsUpdateRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksSubscriptionsUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksSubscriptionsUpdate(request, requestOptions));
    }

    private async __postV1WebhooksSubscriptionsUpdate(
        request: NordletApi.PostV1WebhooksSubscriptionsUpdateRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksSubscriptionsUpdateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/update",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksSubscriptionsUpdateResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/update",
        );
    }

    /**
     * @param {NordletApi.PostV1WebhooksSubscriptionsDeleteRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksSubscriptionsDelete({
     *         id: "id"
     *     })
     */
    public postV1WebhooksSubscriptionsDelete(
        request: NordletApi.PostV1WebhooksSubscriptionsDeleteRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksSubscriptionsDeleteResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksSubscriptionsDelete(request, requestOptions));
    }

    private async __postV1WebhooksSubscriptionsDelete(
        request: NordletApi.PostV1WebhooksSubscriptionsDeleteRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksSubscriptionsDeleteResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/delete",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksSubscriptionsDeleteResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/delete",
        );
    }

    /**
     * @param {NordletApi.PostV1WebhooksDeliveriesListRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksDeliveriesList()
     */
    public postV1WebhooksDeliveriesList(
        request: NordletApi.PostV1WebhooksDeliveriesListRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksDeliveriesListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksDeliveriesList(request, requestOptions));
    }

    private async __postV1WebhooksDeliveriesList(
        request: NordletApi.PostV1WebhooksDeliveriesListRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksDeliveriesListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/deliveries/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksDeliveriesListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/webhooks/deliveries/list");
    }

    /**
     * @param {NordletApi.PostV1WebhooksDeliveriesRedeliverRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.postV1WebhooksDeliveriesRedeliver({
     *         id: "id"
     *     })
     */
    public postV1WebhooksDeliveriesRedeliver(
        request: NordletApi.PostV1WebhooksDeliveriesRedeliverRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.PostV1WebhooksDeliveriesRedeliverResponse> {
        return core.HttpResponsePromise.fromPromise(this.__postV1WebhooksDeliveriesRedeliver(request, requestOptions));
    }

    private async __postV1WebhooksDeliveriesRedeliver(
        request: NordletApi.PostV1WebhooksDeliveriesRedeliverRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.PostV1WebhooksDeliveriesRedeliverResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/deliveries/redeliver",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.PostV1WebhooksDeliveriesRedeliverResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/deliveries/redeliver",
        );
    }
}
