// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as NordletApi from "../../../index.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @param {NordletApi.SubscriptionsCreateWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.subscriptionsCreate({
     *         url: "url",
     *         events: ["agreement.invoice_generated"]
     *     })
     */
    public subscriptionsCreate(
        request: NordletApi.SubscriptionsCreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.SubscriptionsCreateWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__subscriptionsCreate(request, requestOptions));
    }

    private async __subscriptionsCreate(
        request: NordletApi.SubscriptionsCreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.SubscriptionsCreateWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.SubscriptionsCreateWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/create",
        );
    }

    /**
     * @param {NordletApi.SubscriptionsListWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.subscriptionsList()
     */
    public subscriptionsList(
        request: NordletApi.SubscriptionsListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.SubscriptionsListWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__subscriptionsList(request, requestOptions));
    }

    private async __subscriptionsList(
        request: NordletApi.SubscriptionsListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.SubscriptionsListWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.SubscriptionsListWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/list",
        );
    }

    /**
     * @param {NordletApi.SubscriptionsUpdateWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.subscriptionsUpdate({
     *         id: "id"
     *     })
     */
    public subscriptionsUpdate(
        request: NordletApi.SubscriptionsUpdateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.SubscriptionsUpdateWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__subscriptionsUpdate(request, requestOptions));
    }

    private async __subscriptionsUpdate(
        request: NordletApi.SubscriptionsUpdateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.SubscriptionsUpdateWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/update",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.SubscriptionsUpdateWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/update",
        );
    }

    /**
     * @param {NordletApi.SubscriptionsDeleteWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.subscriptionsDelete({
     *         id: "id"
     *     })
     */
    public subscriptionsDelete(
        request: NordletApi.SubscriptionsDeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.SubscriptionsDeleteWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__subscriptionsDelete(request, requestOptions));
    }

    private async __subscriptionsDelete(
        request: NordletApi.SubscriptionsDeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.SubscriptionsDeleteWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/subscriptions/delete",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.SubscriptionsDeleteWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/subscriptions/delete",
        );
    }

    /**
     * @param {NordletApi.DeliveriesListWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.deliveriesList()
     */
    public deliveriesList(
        request: NordletApi.DeliveriesListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.DeliveriesListWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deliveriesList(request, requestOptions));
    }

    private async __deliveriesList(
        request: NordletApi.DeliveriesListWebhooksRequest = {},
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.DeliveriesListWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/deliveries/list",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.DeliveriesListWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/webhooks/deliveries/list");
    }

    /**
     * @param {NordletApi.DeliveriesRedeliverWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link NordletApi.BadRequestError}
     * @throws {@link NordletApi.UnauthorizedError}
     * @throws {@link NordletApi.PaymentRequiredError}
     * @throws {@link NordletApi.ForbiddenError}
     * @throws {@link NordletApi.NotFoundError}
     * @throws {@link NordletApi.ConflictError}
     * @throws {@link NordletApi.ContentTooLargeError}
     * @throws {@link NordletApi.UnprocessableEntityError}
     * @throws {@link NordletApi.TooManyRequestsError}
     * @throws {@link NordletApi.InternalServerError}
     *
     * @example
     *     await client.webhooks.deliveriesRedeliver({
     *         id: "id"
     *     })
     */
    public deliveriesRedeliver(
        request: NordletApi.DeliveriesRedeliverWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<NordletApi.DeliveriesRedeliverWebhooksResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deliveriesRedeliver(request, requestOptions));
    }

    private async __deliveriesRedeliver(
        request: NordletApi.DeliveriesRedeliverWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<NordletApi.DeliveriesRedeliverWebhooksResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.NordletApiEnvironment.Production,
                "v1/webhooks/deliveries/redeliver",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as NordletApi.DeliveriesRedeliverWebhooksResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new NordletApi.BadRequestError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new NordletApi.UnauthorizedError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new NordletApi.PaymentRequiredError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new NordletApi.ForbiddenError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new NordletApi.NotFoundError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new NordletApi.ConflictError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 413:
                    throw new NordletApi.ContentTooLargeError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new NordletApi.UnprocessableEntityError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new NordletApi.TooManyRequestsError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new NordletApi.InternalServerError(
                        _response.error.body as NordletApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.NordletApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/webhooks/deliveries/redeliver",
        );
    }
}
