// This file was auto-generated by Fern from our API Definition.

export interface ConvertLeadsResponse {
    lead: ConvertLeadsResponse.Lead;
    partnerId: string;
}

export namespace ConvertLeadsResponse {
    export interface Lead {
        id: string;
        name: string;
        contactName: string | null;
        email: string | null;
        phone: string | null;
        website: string | null;
        countryCode: string | null;
        sourceId: string | null;
        sourceName: string | null;
        typeId: string | null;
        typeName: string | null;
        status: Lead.Status;
        estimatedValue: string | null;
        currency: string;
        description: string | null;
        assignedUserId: string | null;
        partnerId: string | null;
        convertedAt: string | null;
        createdAt: string;
        updatedAt: string;
    }

    export namespace Lead {
        export const Status = {
            New: "new",
            Contacted: "contacted",
            Qualified: "qualified",
            Lost: "lost",
            Converted: "converted",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
