// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         integration: "integration",
 *         name: "name",
 *         email: "email"
 *     }
 */
export interface IntegrationRequestsPublicRequest {
    integration: string;
    name: string;
    company?: string;
    email: string;
    details?: string;
    website?: string;
}
