// This file was auto-generated by Fern from our API Definition.

export interface PostV1HrContractsListResponse {
    rows: PostV1HrContractsListResponse.Rows.Item[];
    page: number;
    pageSize: number;
    total: number;
}

export namespace PostV1HrContractsListResponse {
    export type Rows = Rows.Item[];

    export namespace Rows {
        export interface Item {
            id: string;
            employeeId: string;
            positionId: string | null;
            departmentId: string | null;
            scheduleId: string | null;
            agreementId: string | null;
            contractNo: string;
            type: Item.Type;
            startDate: string;
            endDate: string | null;
            endReason: string | null;
            baseSalary: string;
            salaryType: Item.SalaryType;
            workHours: string;
            workHoursUnit: Item.WorkHoursUnit;
            status: Item.Status;
            notes: string | null;
            createdAt: string;
        }

        export namespace Item {
            export const Type = {
                Permanent: "permanent",
                FixedTerm: "fixed_term",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            export const SalaryType = {
                Monthly: "monthly",
                Hourly: "hourly",
                Weekly: "weekly",
                Daily: "daily",
                Yearly: "yearly",
            } as const;
            export type SalaryType = (typeof SalaryType)[keyof typeof SalaryType];
            export const WorkHoursUnit = {
                Day: "day",
                Week: "week",
            } as const;
            export type WorkHoursUnit = (typeof WorkHoursUnit)[keyof typeof WorkHoursUnit];
            export const Status = {
                Active: "active",
                Ended: "ended",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
