// This file was auto-generated by Fern from our API Definition.

export interface PostV1HrPositionsUpdateResponse {
    id: string;
    code: string | null;
    name: string;
    translations: Record<string, PostV1HrPositionsUpdateResponse.Translations.Value | null> | null;
}

export namespace PostV1HrPositionsUpdateResponse {
    export namespace Translations {
        export interface Value {
            name: string;
        }
    }
}
