// This file was auto-generated by Fern from our API Definition.

export interface PostV1HrEmployeesCreateResponse {
    id: string;
    code: string | null;
    firstName: string;
    lastName: string;
    personalCode: string | null;
    birthDate: string | null;
    email: string | null;
    phone: string | null;
    address: PostV1HrEmployeesCreateResponse.Address | null;
    iban: string | null;
    socialInsuranceNo: string | null;
    socialInsuranceStart: string | null;
    hireDate: string | null;
    terminationDate: string | null;
    applyNpd: boolean;
    npdOverride: string | null;
    pensionAccumulation: boolean;
    status: PostV1HrEmployeesCreateResponse.Status;
    notes: string | null;
    attributes: PostV1HrEmployeesCreateResponse.Attributes.Item[] | null;
    createdAt: string;
}

export namespace PostV1HrEmployeesCreateResponse {
    export interface Address {
        street?: string | undefined;
        city?: string | undefined;
        postalCode?: string | undefined;
        countryCode?: string | undefined;
    }

    export const Status = {
        Active: "active",
        Terminated: "terminated",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Attributes = Attributes.Item[];

    export namespace Attributes {
        export interface Item {
            name: string;
            value: string;
        }
    }
}
