// This file was auto-generated by Fern from our API Definition.

export interface PostV1HrPositionsCreateResponse {
    id: string;
    code: string | null;
    name: string;
    translations: Record<string, PostV1HrPositionsCreateResponse.Translations.Value | null> | null;
}

export namespace PostV1HrPositionsCreateResponse {
    export namespace Translations {
        export interface Value {
            name: string;
        }
    }
}
